### ISSUE TITLE
Is where a way to integrate with Iron-router?

### ISSUE THREAD

**Issue by 5m1l3** [tomitrescak/meteor-uploads#101]
Is where a way to integrate upload-server with Iron-router , i always get access denied on '/upload' path, but upload folder does not exist on filesystem. Need example, please.

**Comment by wlundgren** [comment]
I am using with Iron router and have no problem. Try cheking folder permissions and configuration.

**Comment by tomitrescak** [comment]
True, this package is router agnostic, where routes can be configured by both flow and iron router.
