### ISSUE TITLE
502 proxy error, apache and mup

### ISSUE THREAD

**Issue by lowenf** [tomitrescak/meteor-uploads#102]
Hi! First of all thanks for the work on this beautiful package!

Now I'm getting a 502 proxy error on production server:
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /upload.
Reason: Error reading from remote server
502 Proxy Error @ 18.0 MB / sec

locally I have no problem and all the code works fine. Now I use MUP to deploy my app to a ubuntu with apache. 

I use mup to log the errors:
[95.85.63.50] events.js:72[95.85.63.50]
[95.85.63.50]         throw er; // Unhandled 'error' event[95.85.63.50]
[95.85.63.50]  [95.85.63.50]  [95.85.63.50]  [95.85.63.50]  [95.85.63.50]           ^
[95.85.63.50] Error: spawn ENOENT[95.85.63.50]
[95.85.63.50]     at errnoException (child_process.js:1011:11)[95.85.63.50]
[95.85.63.50]     at Process.ChildProcess._handle.onexit (child_process.js:802:34)[95.85.63.50]
[95.85.63.50] error: Forever detected script exited with code: 8[95.85.63.50]
[95.85.63.50] error: Script restart attempt #1[95.85.63.50]

I gave the /uploads and /uploads/tmp dirs chmod 777 rights. 

I see renaming the file works, but creating different versions does not. 
Been trying to fix this for hours and feel clueless. Do you have a suggestion?

`/server/init.js`
UploadServer.init({
		tmpDir: process.env.PWD + '/.uploads/tmp',
		uploadDir: process.env.PWD + '/.uploads/', 
		checkCreateDirectories: true,
		maxPostSize: 2500000, //2.5MB
		maxFileSize: 2500000, //2.5MB
		imageVersions: {
			bigPicture: {
				width: 800, 
				height: 600
			},
			thumbnailBig: {
				width: 300, 
				height: 300
			}, 
			thumbnailSmall: {
				width: 150, 
				height: 150
			}
		},
		getFileName: function(fileInfo, formData) {
			// rename file with userid_filename
			return formData._id +'_'+ fileInfo.name;
		}
	});

**Comment by lowenf** [comment]
somehow a friend of mine fixed the 502 error. But now instead I have a 503. I gave the ./uploads/ and ./uploads/tmp dir's a chmod of 777.. .what else could be wrong? some other server setting I missed? I'll ask this on stackoverflow as well.

**Comment by tomitrescak** [comment]
These errors usually refer to:

* Security Issues with write permissions to directories (add permissions to meteoruser)
* Failing imagemagick - not installed, bad configuration
* Header problem on nginx or apache proxy
* Cross domain problems

Usually you can find all info in the console.

**Comment by lowenf** [comment]
so I feel really dumb for this.. but all I needed was a 

    sudo apt-get install imagemagick

I thought the node module was able to do the same, guess again.

**Comment by tomitrescak** [comment]
Glad you worked it out!
