### ISSUE TITLE
How do I remove Bootstrap?

### ISSUE THREAD

**Issue by batjko** [tomitrescak/meteor-uploads#103]
Hi,

I'm trying to build a simple UI component for a file upload, as part of a wider application, so I'm testing out this example app, which is pretty promising, btw.

I'd like to use the Semantic version and the ReadMe says it should look better if Bootstrap isn't also used.
![image](https://cloud.githubusercontent.com/assets/7287076/8261483/e1d0c130-16c2-11e5-8734-f7d7ab94567e.png)

So what do I need to do to remove the Bootstrap parts? Do I simply delete a Meteor package?

**Comment by tomitrescak** [comment]
Yes;) just remove the package.

**Comment by batjko** [comment]
Sorry for the late reply, thank you for the tip!
