### ISSUE TITLE
How to change language of "browse" button in tomi:uploader package?

### ISSUE THREAD

**Issue by hrhitesh** [tomitrescak/meteor-uploads#104]
Hello,

I'm using this package to upload image. But i have some issues when using tap:i18n package to translate  text. As i came to know that this is a default browser text and in some of community they also give answer that this can not be changed. So is there any solution to change this "Browse" text?

Thanks,

**Comment by louwers** [comment]
I'm wondering about this myself! Are you sure it uses the default browser language? I set my browser language to Dutch and stil it shows the English words. It would be brilliant if this plugin could use t9n localization like other packages, so we could set the language ourselves.

**Comment by hrhitesh** [comment]
it's not using default browser language but it's using default browser text.

**Comment by tomitrescak** [comment]
I have just added support for the localisation. It is not reactive, but only few packages support reactive language change. Please refer to the following documentation:

### Localisation

All texts of the upload control can be set via following setting:

```javascript
Uploader.localisation = {
    browse: "Browse",
    cancelled: "Cancelled",
    remove: "Remove",
    upload: "Upload",
    done: "Done",
    cancel: "Cancel"
}
```

**Comment by louwers** [comment]
Thanks!

**Comment by hrhitesh** [comment]
This does not works, where to write this in init.js file?
