### ISSUE TITLE
Modify file before uploading

### ISSUE THREAD

**Issue by louwers** [tomitrescak/meteor-uploads#105]
Is it possible to modify the file using the `validate` callback? Like so:

    validate: function (file) {
	  // file modifications, allow the user to crop it, etc.
      // ...
	  return file;
    }

If not, I would like to make a feature request for this. It would make this package massively more powerful. Thanks!

**Comment by tomitrescak** [comment]
This would make a wonderfull addition. But am currently out of capacity to do such extensions. But it should be fairly simple. It's all described [here](https://github.com/blueimp/jQuery-File-Upload/wiki/Client-side-Image-Resizing) as a plugin to jquery file upload.

What needs to be done is the configuration of uploader [here](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L178-L218)

**Comment by irrigator** [comment]
I need to use canvas to resize the picture before uploading. After reading the code that you point to, I'm still confused about where I should add my resizing code.
The idea is I need to get the file object, use a FileReader to pass the data url to a Image object, use canvas to resize the picture and finally pass a Blob directly to the FormData of the uploader.
Could you please tell me where should I put my code? Thanks a lot.

**Comment by tomitrescak** [comment]
The `validate` callback has been already implemented. My guess that is the best place to put your code. Please check out the documentation for client side validation here [https://github.com/tomitrescak/meteor-uploads](https://github.com/tomitrescak/meteor-uploads). In that callback you get reference to the file that will be uploaded.
