### ISSUE TITLE
Using just the frontend api with a separate server package

### ISSUE THREAD

**Issue by pdiniz13** [tomitrescak/meteor-uploads#106]
Hi, I'm using a server package which uploads the images directly to an azure cdn, is there a way to use you front end package with a different server package? I can format the responses so it fits with what the client expects but I would just need to know where to plug in the connection between the client and the server.

**Comment by tomitrescak** [comment]
Theoretically this should be fairly simple. 
You need to override the [Uploader.startUpload](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L54-L102) function.

If you manage to add another provider, would you consider adding a Pull Request?
Thanks.

**Comment by tomitrescak** [comment]
Please close if I answered your question.
