### ISSUE TITLE
Ehancement request: option to turn off console logging

### ISSUE THREAD

**Issue by proehlen** [tomitrescak/meteor-uploads#107]
First, thank you for your extremely handy and easy to use package.

If you are considering enhancement requests, could we have an option to turn off console logging of things this package does?  Unless I'm actively debugging a problem with file uploads, all of these messages tend to distract me when resolving other problems:

Server:
![screen shot 2015-06-27 at 5 46 49 pm](https://cloud.githubusercontent.com/assets/8384068/8391677/e3425096-1cf4-11e5-87a0-088f86244e29.png)

Client:
![screen shot 2015-06-27 at 5 46 35 pm](https://cloud.githubusercontent.com/assets/8384068/8391678/e34bf4ac-1cf4-11e5-8acc-81fe01df167f.png)

**Comment by tomitrescak** [comment]
Valid point. It is solved in next release of both server and client.
The client is configurable via:

```javascript
Uploader.logLevel = Uploader.logLevels.debug; 
```
