### ISSUE TITLE
502 Gateway error

### ISSUE THREAD

**Issue by namirsab** [tomitrescak/meteor-uploads#108]
I've followed the issue #40 but i cant make it.

Hello Everybody!
I have the same problem. I've tried everything it's written here. At first I had my .uploads directory in the /home/user/bundle/ directory ( the directory of the packaged app).
I tried all what you said but it didn't work. It uploads the images but when it callls the finished calllback it gives me a 502 error bad gateway.
I changed the dir to opt/appname/... as I've read here but it's still not working. It gives me the same error when it finished and it uploads the photo but not creates the thumbnail, but does not let me get the fileInfo in the callback.
When i look the nginx log it says this:
# upstream prematurely closed connection while reading response header from upstream
So I don't know what's happening. I'm deploying in a DigitalOcean droplet with Ubuntu 14.04.

This is the init function:

 UploadServer.init({
        tmpDir: '/opt/appname' + '/.uploads/tmp',
        uploadDir: '/opt/appname' + '/.uploads/',
        checkCreateDirectories: true,    //create the directories for you
        imageVersions: {thumbnail: {width: 300, height: 300}},
        crop: true,
        overwrite:true,
})

I'm not using mup, I've followed this tutorial:
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx

**Comment by namirsab** [comment]
The problem was I hadn't imagemagick installed. Fixed with this.

**Comment by appjitsu** [comment]
@namirsab when the site gets deployed, what is the path of your .uploads directory and permissions? I am having similar problems through mupx.
