### ISSUE TITLE
Connection reset problem

### ISSUE THREAD

**Issue by batamar** [tomitrescak/meteor-uploads#110]
Obviously it is not this package's problem. But i thought it is the best place to ask this question. A team with nearly 100 members using our app that using this package to upload files. On some person's computer (others are fine)  after uploading files (about 1 minute later) there is a error (connection reset) in the browser console and uploader displaying failed message. Any suggesstions ?

**Comment by tomitrescak** [comment]
Batamar, this ... I have nbo idea .. I'm really sorry. It's deployment specific problem .. did you manage to solve it? 

I'll close this for now.

**Comment by onbjerg** [comment]
I have the exact same problem. My client is pissed.

**Comment by tomitrescak** [comment]
Try to contact @batamar .
I am using this package in several projects for two years and have not bumped into this problem.
It has to has something with your server configuration, possibly with domain policies?

**Comment by onbjerg** [comment]
I found out. It was something with permissions, although it didnt appear in the logs. There should be some more error messages to prevent this confusion.

**Comment by batamar** [comment]
@onbjerg Can you explain more detailed ?.

**Comment by onbjerg** [comment]
Yes. I was using meteor-up, and the user I ran Meteor on did not have permissions to my upload folder. In order to resolve it, I ran these commands:

``chown -R meteoruser .uploads``
``chmod -R 755 .uploads``

And it worked great.
