### ISSUE TITLE
Race condition to display image

### ISSUE THREAD

**Issue by j6k4m8** [tomitrescak/meteor-uploads#111]
I'm curious how others have dealt with this, or if there is an accepted, good way of dealing with this:

> Upload an image
> Immediately display that image on the same page

The outcome I most commonly see is the 'image-not-found' broken-link placeholder, suggesting that I updated the `src` attribute automatically (using Meteor), *before* the upload and cropping/conversion was finished.

Thoughts? Hoping there's something built-in that I'm just missing here, and if not, I'd be interested in contributing to a fix.

**Comment by tomitrescak** [comment]
Well, you can show the image that you get in the `validate` callback on client.
Otherwise you have to wait for server upload and url.
