### ISSUE TITLE
Upload Button does nothing

### ISSUE THREAD

**Issue by jpmolinamatute** [tomitrescak/meteor-uploads#112]
Hello!

I have followed the instructions but when I click on upload button nothing happen (I can see the style changing but that's it)

I'm using the latest meteor version, with default jQuery,  I ran `$.support.fileInput` and returned "true"

this is the configuration that I'm using 

// server/init.js

Meteor.startup(function () {
    "use strict";

    UploadServer.init({
        tmpDir: process.env.PWD + "/.uploads/tmp",
        uploadDir: process.env.PWD + "/.uploads/",
        checkCreateDirectories: true //create the directories for you
    });
});

and

Template.dashboard.helpers({
    specificFormData: function() {
        "use strict";

        return {
            id: new Mongo.ObjectID(),
            //other: this.other,
            hard: "Lolcats"
        };
    }
});

am I doing something wrong or am I missing something?

thanks in advance for your time, help and this package :-)

**Comment by jpmolinamatute** [comment]
nevermind,  this is the same as issue 38, the browse button was hidden and I thought upload button did both browse for file and upload them.

I just ran $('.btn-file').removeAttr('style'); and everything works and it suppose to.


you can close this ticket

**Comment by Jusdev89** [comment]
@jpmolinamatute hey how did you get $('.btn-file').removeAttr('style'); to work. it keeps telling me i have an unexpected token (

**Comment by batjko** [comment]
Tip: you can always close a ticket yourself, there's a button for it next to the "Comment" button at the bottom.

**Comment by tomitrescak** [comment]
Does anyone know why is this happening? Is it a bug? Sorry .. just no time right now :/ Can anyone do PR maybe? I would really appreciate it!

**Comment by tomitrescak** [comment]
Nevermind. 2.1.7 resolves this issue. Sorry about that.
