### ISSUE TITLE
.uploads directory created with root ownership, inaccessible 

### ISSUE THREAD

**Issue by gleslie2008** [tomitrescak/meteor-uploads#114]
Hi,

When using `meteor-uploads`, the directories specified to be created by `tmpDir` and `uploadDir` in:
```javascript
  UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/images/',
    checkCreateDirectories: true,
    ...
  });
```
are created with the owner `root` rather than the owner that the meteor application is running as.  Then, the meteor application does not have authorization to modify files in the `.uploads/` directory. Running on Ubuntu 14.04 and using [Meteor Up](https://github.com/arunoda/meteor-up) to deploy.

Any ideas?  We're having to manually change the ownership of the `.uploads/` directory on each deployment now.

Thanks.

**Comment by tomitrescak** [comment]
Directories are created by user who is running the meteor process, or at least that is how it shall work by default. It is a meteor process that is creating these directories, no authorisation is performed.

**Comment by MomchilGorchev** [comment]
Hi, thanks for this package!
One issue though, deploying with `meteor deploy` gives this error:

```

[Thu Jul 16 2015 09:38:20 GMT+0000 (UTC)] WARNING Error: EACCES, permission denied '/.uploads/'
at Object.fs.mkdirSync (fs.js:654:18)
at checkCreateDirectory (packages/tomi:upload-server/upload_server.js:480:1)
at Object.UploadServer.init (packages/tomi:upload-server/upload_server.js:98:1)
at app/server/AppEngine.js:10:18
....
```
The settings are looking like that:
```javascript
UploadServer.init({
        tmpDir: process.env.PWD + '/.uploads/tmp',
        uploadDir: process.env.PWD + '/private/',
        checkCreateDirectories: true //create the directories for you
    });
```
Is it something im doing wrong? Thanks in advance

**Comment by tomitrescak** [comment]
So, is the problem solved? 
Can you confirm that creating folders manually resolved your problem? Thanks.

**Comment by MomchilGorchev** [comment]
Confirmed, creating the folder manually solved the issue.
Thanks!
