### ISSUE TITLE
relative image url's

### ISSUE THREAD

**Issue by lowenf** [tomitrescak/meteor-uploads#115]
Thanks again for creating this awesome package!

all url's right now are absolute (see example) when using MUP (even though I set the enviroment variable ROOT_URL to myDomainName): 
{ 
	name: 'SCqsTggwxkf8tPfuB_bali.jpg',
	path: '/SCqsTggwxkf8tPfuB_bali.jpg',
	size: 300587,
	type: 'image/jpeg',
	error: null,
	url: 'http://localhost:3000/upload/SCqsTggwxkf8tPfuB_bali.jpg',
	bigPictureUrl: 'http://localhost:3000/upload/bigPicture/SCqsTggwxkf8tPfuB_bali.jpg',
	thumbnailBigUrl: 'http://localhost:3000/upload/thumbnailBig/SCqsTggwxkf8tPfuB_bali.jpg',
	thumbnailSmallUrl: 'http://localhost:3000/upload/thumbnailSmall/SCqsTggwxkf8tPfuB_bali.jpg' 
}

Is it possible to have relative url's instead? Right now i'm simply splitting them and overwriting the key values in the object.

**Comment by tomitrescak** [comment]
My pleasure. "Path" contains a relative path to your upload url.

**Comment by lowenf** [comment]
I meant the path's to all the converted images. 

or you mean you would include a different path in HTML? Like so:
<img src="/upload/bigPicture/{{path}}">

you can see your package in action @ dateanomad.net (my new project). I still want to include a loader for the images. The image conversion seems to take quite a long time.

**Comment by tomitrescak** [comment]
What you do seems fine to me. Server does not return paths to thumbnails unfortunatelly. This you shall be able to solve easily, just like you did.
