### ISSUE TITLE
UploadServer

### ISSUE THREAD

**Issue by frankapimenta** [tomitrescak/meteor-uploads#117]
I am having this strange behavior:

Meteor.methods
  delete: ->(image)
   UploadServer.delete(image.path)

in browser's console:

ReferenceError: UploadServer is not defined

**Comment by tomitrescak** [comment]
Nothing too strange about this. You cannot access server object on the client. UploadServer is a server object. And Frank, please, if the whole component is written in Javascript be kind and avoid using coffee script. Thanks!

PS: What you have to do is to call a server method in which you will use UploadServer object to delete the image.

**Comment by frankapimenta** [comment]
Maybe there was a misunderstanding. I do not call the method in the browser's console.

The delete Meteor method is (server method) called in Uploader.finished method. 

Meteor.startup(function() {
  Uploader.finished = function(index, file_info, template) {
    Meteor.call 'deleteImage', template.data.formData.id, function(error, response) {
       // error treatment
   }
}
}

Meteor.method 'deleteImage', function(id) {
  obj = Images.findOne(id).
  UploadServer.delete(obj.path)
}

In the browser's console I have the error shown after the method is called even though image is deleted.

**Comment by tomitrescak** [comment]
there is no way you will see server errors in the browser console. You are executing your code on client not on server. Make sure you wrap everything in `Meteor.isServer`. If your code is stored in non "server" folder it will be executed on client.

**Comment by frankapimenta** [comment]
I think the same.
Will inspect further.
Thank you for your time.
