### ISSUE TITLE
Adding imageVersions leads to no url in fileInfo

### ISSUE THREAD

**Issue by fellz** [tomitrescak/meteor-uploads#118]
Hi
As i added imageVersions to server init i have no url in fileInfo object
Is this a bug  ?
```
Meteor.startup(function () {
    UploadServer.init({
      tmpDir: process.env.PWD + '/.uploads/tmp',
      uploadDir: process.env.PWD + '/.uploads/',
      checkCreateDirectories: true, //create the directories for you
      imageVersions: {thumbnailSmall: {width: 200, height: 150}},
      finished: function(fileInfo, formFields){
        var userId = formFields.id
        Meteor.users.update( { _id: userId}, { $set: { 'profile.pic': fileInfo }} )
    }
  })
});
```
fileInfo: 
"pic" : {
            "name" : "me.jpg",
            "path" : "/me.jpg",
            "size" : 88520,
            "type" : "image/jpeg",
            "error" : null
        }
btw there is no Demo url on the main page. It's just deleted ? Examples would be very helpful

**Comment by Xample** [comment]
I think it's a bug as well, the fileInfo is okay on the client site's callback but resolved only after the ```finished```callback on the client side. No url seems to be resolved before going to the ```end```state event of the upload process.

**Comment by Xample** [comment]
@fellz here is my current workaround, I just rebuild the url my self…

```js
function url(fileInfo)
{
    var uploaderFolder = Uploader.uploadUrl;
    var filePath = fileInfo.path;
    var fullPath = uploaderFolder+"/"+filePath;
    var cleanPath = (_.compact(fullPath.split("/"))).join("/");
    var absoluteURL = Meteor.absoluteUrl(cleanPath);
    return encodeURI(absoluteURL);
}

**Comment by tomitrescak** [comment]
It's there, just update the server and you shall be good to go. Sorry about that.
