### ISSUE TITLE
getDirectory called twice with different parameters

### ISSUE THREAD

**Issue by Xample** [tomitrescak/meteor-uploads#119]
On the server the method
```js
getDirectory: function (fileInfo, formData)
```
is called:
- one time from
```js
    // we can store files in subdirectories
    var folder = options.getDirectory(fileInfo, this.formFields);
```
 right after the upload to know where to store it, the fileInfo parameter is an object at this time

- one time later from
```js
FileInfo.prototype.initUrls = function (req, form) {
  if (!this.error) {
    var that = this,
      subDirectory = options.getDirectory(this.name, form.formFields),
```
 to retrieve the url, the fileInto is only a String at this time, containing the name…

Therefore as I am returning the right subfolder based on the fileinfo (and not the name) this is a real issue.

The fix is to replace the line above by:
```js
      subDirectory = options.getDirectory(that, form.formFields),
```

**Comment by Xample** [comment]
I suggested a fix here:
https://github.com/tomitrescak/meteor-tomi-upload-server/pull/12

**Comment by tomitrescak** [comment]
Great fix! I'll merge it ASAP. Am on mobile now.

**Comment by tomitrescak** [comment]
Fixed in latest. Thanks again.
