### ISSUE TITLE
How do I do add events on upload?

### ISSUE THREAD

**Issue by rozick** [tomitrescak/meteor-uploads#121]
First of all -- very cool add on and thanks. I saw in the documentation you wrote how to add the upload info to a collection. My question is, what if I want to just temporarily save what the user uploaded as a variable, like the file ID etc. to be added to a collection later?

Like if this were a simple submit. I could do Template.template.events { click button function { var fileid=_id, var currentUser = Meteir.userId etc...

How would I be able to just store individual variables on upload without adding to a collection using this add on? Thanks!

**Comment by tomitrescak** [comment]
Well, you can use a `validate` callback and store it wherever you would like (Session, Local Store ...). Does this answer your question?

**Comment by rozick** [comment]
Thanks for getting back so quick! It looks like I can just use your So I used the helper with formdata like you have in your readme to store the variables there. Now I just want to add the formdata to a variable or even just insert it using your Uploader.finished() function.

I see you can do something like Uploads.insert(file) after Uploader.finished() is called, but how can you specifically insert or store formdata as a variable in that function? That should solve my issue thanks!

**Comment by tomitrescak** [comment]
Glad you solved it! I'll close this for now, please reopen if necessary.
