### ISSUE TITLE
Getting 503 and 403 errors

### ISSUE THREAD

**Issue by SturmDrangAltaar** [tomitrescak/meteor-uploads#122]
Hi there,

I've created the required file directories (and made them word-writable just in case), but when I try the upload, the following happens:
I either get a 503 (Service unavailable error) - This happens when using the frontend helper
Or if I try to access the url (some-app.com/upload) directly, I get a 403 Access Denied

All I get in the console on the server is:
I20150730-00:24:47.744(2)? ERROR
I20150730-00:24:47.745(2)? [Error: Request aborted]

Not sure what I'm missing in the config here?
```javascript
UploadServer.init({
	    tmpDir: process.env.PWD + '/.uploads/tmp',
		uploadDir: process.env.PWD + '/.uploads/',
		getFileName: function(fileInfo, formData) {
			return 'myapp_'+ fileInfo.name;
		},
		mimeTypes: {
			"jpeg": "image/jpeg",
		"jpg": "image/jpeg",
		"png": "image/png"
		},
		maxPostSize: 10000,
		maxFileSize: 10000,
		checkCreateDirectories: true //create the directories for you
	  })
```

Oh, and I've tested that process.env.PWD returns the correct path as well.

Any help would be greatly appreciated. Thanks!

EDIT:
Got it working brilliantly on localmachine, but it's bombing on the server.
First run: Cross-domain error. I think this was because the site is running on IP:8000 and trying to access IP/upload
Second run: So I removed the absoluteURL config option and tried again. This time the URL is correct (includes the port), but I get a net::ERR_CONNECTION_REFUSED error.
Print out below:
```
net::ERR_CONNECTION_REFUSEDsend @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:47ie.extend.ajax @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:47u @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:244e.widget._onSend @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:244(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:244n.submit @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:244(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:245ie.extend.each @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:44s.startUpload @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:245n.buttons.events.click .start @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:245(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:66e._withTemplateInstanceFunc @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:66(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:66(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:65c._withCurrentView @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:65(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:65(anonymous function) @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:65ie.event.dispatch @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:46g.handle @ 
bc3e2aa363a737c01046a85bf3308a6136e904c5.js:46
```

**Comment by batjko** [comment]
Permissions thing on that `.uploads` folder, no doubt.
Have you tried god rights temporarily, just to see if that makes a difference?

**Comment by SturmDrangAltaar** [comment]
Damnit, yeah, was the permissions on the server itself. I'm using mup to deploy, but for some reason it creates the build in /opt/ and the permissions are totally insane. Sorry to bother you all, it's working now on chmod 777, I'll change it when I can figure out which user is running meteor on the server.

**Comment by batjko** [comment]
Cool :+1:

**Comment by SturmDrangAltaar** [comment]
Solved, thanks!
