### ISSUE TITLE
contentType only available on Dropzone?

### ISSUE THREAD

**Issue by richarddewit** [tomitrescak/meteor-uploads#126]
The `contentType` parameter is only available on the Dropzone template. If this is intended, please specify so in the readme, could've saved me some hair-pulling :P

If not, then please fix `upload_boostrap` and `upload_semanticUI` templates so they accept `contentType` as well.

Now when `contentType` is used, it isn't appended to the `formData` parameter and `formData` is undefined.

**Comment by tomitrescak** [comment]
Not sure what do you mean, content type is automatically added to the form data.
As per: https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/templates/upload.js#L23-L28

**Comment by tomitrescak** [comment]
Sorry, you were right. It was a bug. Will be fixed in the next release 2.1.8. I apologise.

**Comment by Temigo** [comment]
I have the same problem with the version 2.4.0 of upload-jquery. Is it supposed to be fixed ?
