### ISSUE TITLE
Suggestions for security on "delete" functionality

### ISSUE THREAD

**Issue by wesyah234** [tomitrescak/meteor-uploads#127]
I'm going to implement some mechanism in the validateRequest function for controlling access to downloads.. however, if I have a delete functionality, I assume I also need to put something in place to prevent unauthorized "deletes" of uploaded files.  Do you have any suggestions? or should I do it the same way as the downloads, and pass through a token I can use to look up the user to see if their resume token is still present in the users collection..??

events on client:
```
Template.fileList.events({
    'click #deleteFileButton ': function (event) {
      Meteor.call('deleteFile', this._id);
    }
  })
```

method defined on server:
```
  Meteor.methods({
    'deleteFile': function (_id) {
      check(_id, String);

      var upload = Uploads.findOne(_id);
      if (upload == null) {
        throw new Meteor.Error(404, 'Upload not found'); // maybe some other code
      }
// NOTE: we should also validate here and make sure user is logged in by passing a token through??
      UploadServer.delete(upload.path);
      Uploads.remove(_id);
    }
  })
```

**Comment by tomitrescak** [comment]
What you can do is use some kind of token which you issue on server for a specific user and pass it down to client. Then, when deleting the file, attach the token to the deletion request and compare on server if that given user has access to delete that file. 

I hope this helped. Please reopen if necessary,

**Comment by wesyah234** [comment]
yes it helps, I'm going to do something like this for controlling access to downloads as well.
