### ISSUE TITLE
Is there a way to hide the progress bars after upload?

### ISSUE THREAD

**Issue by wesyah234** [tomitrescak/meteor-uploads#128]
So, after I upload, I'm still on the same page of the web app, and it is cluttered with the results of the files that were uploaded... I was wondering if there was a way to get these to go away after they were uploaded.

I tried clicking Done, but that doesn't make them go away... thanks!

![screen shot 2015-08-06 at 2 34 13 pm](https://cloud.githubusercontent.com/assets/66566/9121508/4fe93968-3c48-11e5-8c19-32808ccff25a.jpg)

**Comment by tomitrescak** [comment]
You can do it yourself by hooking onto the Done button click, the class to search for is ".doneButton". Possibly clicking on the main Done button, should reset the uploader, but  don't think that resets the queue. 

You need to override the `Uploader.reset` defined [here](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L140-L144).

In that function you have assess to the `queue` holding the current queue and `queueView` which is a reactive variable responsible for re-rendiring of the queue.

Hope this helps. Please reopen if necessary,
