### ISSUE TITLE
UI doesn't work inside bootbox popup

### ISSUE THREAD

**Issue by ssadams11** [tomitrescak/meteor-uploads#129]
```coffeescript
  $(".graph-file-import").click ()->
    bootbox.dialog
      title: "Select a graphML or graphSON file to be uploaded for use in a script"
      message: Blaze.toHTML(Template.GraphUploadPopUp)
      buttons:
        success:
          label: "Done"
          className: "btn-success"
          callback: ()->
            alert 'yahoo'
```
```html
<template name="GraphUploadPopUp">
    <h2>Upload a graphML or graphSON file</h2>
    {{> upload_bootstrap fileTypes=['.graphml','.graphson','.json','.xml'] multiple=true }}
</template>
```

![image](https://cloud.githubusercontent.com/assets/5204570/9126815/3ad6d4da-3c80-11e5-91f3-759500795d6a.png)

Clicking Browse brings up the file chooser, but after selection, nothing shows up in the progress bar and clicking Upload does nothing.

I've verified my setup by using the same {{> upload_bootstrap}} in my top-level Home Template and it all works normally

Any clues?

**Comment by tomitrescak** [comment]
Hi, pleae, if you see that the component is written in Javascript, be of that kind heart and provide examples in javascript. I personally dislike the language, but I respect the preference. Second, your file types list looks suspicious, please check the documentation. Try to download the sources and check your events. My guess that your modal is not opened within the main document HTML, away from the template code and therefore its events are not picked up by Meteor. Check the location of where the HTML of modal is inserted and if it remained in the template. Please reopen if necessary,
