### ISSUE TITLE
503 Service Unavailable right after the upload reaches 100%

### ISSUE THREAD

**Issue by Tralvor** [tomitrescak/meteor-uploads#131]
I literally followed the tutorial line for line on https://github.com/tomitrescak/meteor-uploads and I get a 503 Service Unavailable right after the upload reaches 100%. 
Directories for upload  have rights for writing

W20150810-15:19:45.988(3)? (STDERR) 
W20150810-15:19:45.989(3)? (STDERR) /home/tralvor/mastera/.meteor/local/build/programs/server/packages/tomi_upload-server.js:400
W20150810-15:19:45.989(3)? (STDERR)     folder.replace(/\./g, '');                                                
W20150810-15:19:45.989(3)? (STDERR)            ^
W20150810-15:19:46.000(3)? (STDERR) TypeError: Cannot call method 'replace' of undefined
W20150810-15:19:46.001(3)? (STDERR)     at IncomingForm.<anonymous> (packages/tomi:upload-server/upload_server.js:380:1)
W20150810-15:19:46.001(3)? (STDERR)     at IncomingForm.emit (events.js:98:17)
W20150810-15:19:46.001(3)? (STDERR)     at /home/tralvor/.meteor/packages/tomi_upload-server/.1.2.7.aj1oa6++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:228:12
W20150810-15:19:46.001(3)? (STDERR)     at WriteStream.<anonymous> (/home/tralvor/.meteor/packages/tomi_upload-server/.1.2.7.aj1oa6++os+web.browser+web.cordova/npm/node_modules/formidable/lib/file.js:70:5)
W20150810-15:19:46.001(3)? (STDERR)     at WriteStream.g (events.js:180:16)
W20150810-15:19:46.001(3)? (STDERR)     at WriteStream.emit (events.js:117:20)
W20150810-15:19:46.001(3)? (STDERR)     at finishMaybe (_stream_writable.js:360:12)
W20150810-15:19:46.001(3)? (STDERR)     at afterWrite (_stream_writable.js:280:5)
W20150810-15:19:46.002(3)? (STDERR)     at onwrite (_stream_writable.js:270:7)
W20150810-15:19:46.002(3)? (STDERR)     at WritableState.onwrite (_stream_writable.js:97:5)
W20150810-15:19:46.002(3)? (STDERR)     at fs.js:1695:5
W20150810-15:19:46.002(3)? (STDERR)     at Object.wrapper [as oncomplete] (fs.js:522:5)
=> Exited with code: 8
I20150810-15:19:54.088(3)? seeds launched...  
=> Meteor server restarted

**Comment by batjko** [comment]
This is usually because of an issue with the folders. If you're 100% positive about the permissions being fine, it'll be with the format or location or something that means they can't be reached.

**Comment by Tralvor** [comment]
thanks, resolve this issue with it:
Meteor.startup(function () {
......
getDirectory: function(fileInfo, formData) {
      return '/';
    },
......

**Comment by tomitrescak** [comment]
Glad that you solved it. I'll close this now. If need be, reopen.

**Comment by capensisma** [comment]
@tomitrescak please change the README because it doesn't work if we don't return the '/' there

thanks
