### ISSUE TITLE
getDirectory on server getting called twice.

### ISSUE THREAD

**Issue by bhupesh** [tomitrescak/meteor-uploads#132]
Hi, I have following server code to upload files. I am dynamically changing the file names to uuid. However the `getDirectory` is getting called twice and it was generating `uuid` twice. I couldnt use `getFilename ` here as my sub directories are based on `uuid`

Although I can prevent it using `origName` property check, I was curious why the function will get called twice.

Any help appeciated.

    UploadServer.init({
        tmpDir:     '/tmp'
        uploadDir:  '/upload'
        checkCreateDirectories: true
        acceptFileTypes: /.(jpe?g|png|gif|mp4|mpe?g|webm|mp3|ogg|ogv)$/i
        getDirectory: function (fileInfo, formData) {
          console.log 'getDirectory', fileInfo

          // getDirectory is getting called twice
          if (!fileInfo.origName) {
            extension = path.extname( fileInfo.name )
            fileInfo.origName = path.basename ( fileInfo.name, extension )
            fileInfo.name = Meteor.uuid() + extension

          return fileInfo.name.substr(0, 2) + '/' + fileInfo.name.substr(2,2)
         }
        }
    })

**Comment by tomitrescak** [comment]
It is called from two different locations in code.

https://github.com/tomitrescak/meteor-tomi-upload-server/blob/master/upload_server.js#L299
and
https://github.com/tomitrescak/meteor-tomi-upload-server/blob/master/upload_server.js#L381

So get directory has to return the same directory.
You can pass that uuid from client as part of your form fields.

**Comment by bhupesh** [comment]
Thanks for clarifying.
