### ISSUE TITLE
Caching does not seem to work properly

### ISSUE THREAD

**Issue by n4tiv3pwnst4r** [tomitrescak/meteor-uploads#135]
The package is great and I really liked the visual feedback provided by the interface, but unfortunately I found a file caching issue with the package that ultimately prevented me from being able to use this package in my production application.

No matter what value I configure the package with on startup (using the `cacheTime` configuration parameter), the uploaded file seems to be cached, despite refreshing the browser cache and even stopping and restarting the application. A value of `0` definitely does not seem to disable the file cache as the documentation suggests.

**Comment by tomitrescak** [comment]
You are right! It was a bug. Will be fixed in the next release 1.2.8.
