### ISSUE TITLE
[Error: Request aborted] but not a permission issue

### ISSUE THREAD

**Issue by madhan5000** [tomitrescak/meteor-uploads#136]
Hello there,
This was working before and I can't seem to figure out why uploads stopped working. Here is the error message I get in my sever console.

W20150813-14:09:56.254(-5)? (STDERR) Error: Request aborted
W20150813-14:09:56.254(-5)? (STDERR)     at IncomingMessage.onReqAborted (/home/madhan/.meteor/packages/simple_json-routes/.1.0.3.16mmpp6++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/multiparty/index.js:131:17)
W20150813-14:09:56.255(-5)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20150813-14:09:56.255(-5)? (STDERR)     at abortIncoming (http.js:1916:11)
W20150813-14:09:56.255(-5)? (STDERR)     at Socket.serverSocketCloseListener (http.js:1928:5)
W20150813-14:09:56.256(-5)? (STDERR)     at Socket.emit (events.js:117:20)
W20150813-14:09:56.256(-5)? (STDERR)     at TCP.close (net.js:466:12)

I am running on Ubuntu 14.10. Local virtual machine. I am running as normal user. The package creates directories when I delete it. So I believe it is not permission issue.

Can you please advice?

Thanks in advance.

**Comment by tomitrescak** [comment]
As per several issues raised on this forum. Even though Node.js creates the directories successfully, it is often not accessible by meteor user process. Please create those directories manually and set correct permissions. Check for other solutions on this website in closed issues. Reopen if necessary.

**Comment by madhan5000** [comment]
Thank you for your reply. It is very strange. The same application with 
     
     meteor --production 

uploads the files correctly (though formData is undefined at finished callback).  I am wondering if there is a conflict of packages. The error log I pasted above shows it is at simple_json-routes package. Does your package depend on simple:json-routes? . Any how it might not be an error in your package.

**Comment by madhan5000** [comment]
Ok, I did two things and I am not sure what fixed it. I removed tomi:upload-server and tomi:upload-jquery and added them back. which I believe gave me the latest version.

Also there was an update for simple:json routes

    simple:json-routes                upgraded from 1.0.3 to 1.0.4

it seems to be working now. Thanks !!
