### ISSUE TITLE
changing the uploadUrl for customized accessing

### ISSUE THREAD

**Issue by binarytracer** [tomitrescak/meteor-uploads#137]
Hi there tomi, I have implemented the the package successfully, as of this time the accessing the uploaded image via this url form : http://ww.example.com/upload/image.jpg.

How can i make the image accessing it this url  " http://www.example.com/custom-path/image.jpg?

**Comment by tomitrescak** [comment]
Hi. As per documentation:

```javascript
//file:/client/init.js
Meteor.startup(function() {
  Uploader.uploadUrl = "Your-Base-URL-Instead-Of-Upload"
});
```

And then individual uploads are configured via `Uploader.getDirectory` function.

**Comment by binarytracer** [comment]
actually @tomitrescak, ive tried that already using this config,

//file:/server/init.js
Meteor.startup(function() {
  UploadServer.init({
     uploadUrl: "/pukangkang/",
     ....
  
   })
});

but everytime i access the image like http:www.example.com/pukangkang/image.jpg does not work. Give me this   Oops, looks like there's no route on the client or the server for url: "http://www.example.com/pukangkang/b8e8c670018d5a01.jpg.", hmmm i guess this is somewhat related to iron::router.
