### ISSUE TITLE
show a loader while creating thumbs

### ISSUE THREAD

**Issue by lowenf** [tomitrescak/meteor-uploads#138]
Hey Tomi! once again, my compliments :)

So I created an uploader and have a finished callback. Then reactively I show the images the user has uploaded (including a delete button and more, you can see the results in dateanomad.net if you're curious). But now I noticed when the image is very large, the process of creating thumbnails can takesa while. Because it reactively only shows after the whole image has been formatted. I want to show a loader, but not sure how I can indicate this.

**Comment by tomitrescak** [comment]
You can do following:

1. Use `validate` callback on clinet where you will show the loader animation on client
2. On server, use imagemagick or graphicsmagick to create thumnails for your images
3. In `finished` callback hide the loader animation and show the thumbnail (much smaller in size)

Hope this helps! Please reopen if necessary.
