### ISSUE TITLE
Can we use this plugin to upload assests on s3

### ISSUE THREAD

**Issue by harshal-shinde** [tomitrescak/meteor-uploads#140]
Steps what i am looking for
1.Drag and drop image or browse the asset
2.upload assets to aws s3  

not able to identify that it is useful for me or not

Thanks in advance

**Comment by tomitrescak** [comment]
No. There is a different plugin for S3. This one is aimed at standalone servers. S3 support is planned, but not happenng now.

**Comment by johngonzalez** [comment]
What S3 plugin would you recommend?
