### ISSUE TITLE
How to upload file from native mobile (yes 100% native)

### ISSUE THREAD

**Issue by katopz** [tomitrescak/meteor-uploads#141]
Hi, 

I'm tested and lucky me it's working via js. (Yeah!)
My next task is upload file from native mobile device (don't ask me why) both Android (and iOS later).
So the question is how can I implement this? Any hint or link is welcome.

Thanks!

**Comment by tomitrescak** [comment]
I'm sorry, but this is more of a question for StackOverflow then here, I have no experience with native mobile development :/

**Comment by katopz** [comment]
@tomitrescak  Oh sorry, I'll ask only things that related then, actually file is uploaded but collections not insert so here's my question.

refer to https://github.com/tomitrescak/meteor-uploads/blob/master/client%2Finit.js#L3
```js
Meteor.startup(function() {
  Uploader.finished = function(index, file) {
    Uploads.insert(file);
  }
});
```

This mean when upload file to server is done via `Uploader`, 
we insert file via `Uploads` after that at client am I right?

Why this happen at client btw, I thought when I upload it should be like
```
client [upload] --file--> server [save file then insert collection] 
// and client subscribe for collection update
```
but at present it look like
```
client [upload] --file--> server [save file] --success--> client [insert file] --file--> server [insert file]
```

Sorry to bother, Your sharing is great help for me to accomplish this. I just missing some piece here.

Thanks

**Comment by tomitrescak** [comment]
You can insert data also on server. No issue there, the `finished` callback is running in the Meteor thread. The only problem can be that you do not have access to Meteor.user() on server since it is a server route.
