### ISSUE TITLE
Where the uploaded file gets saved Physcially?

### ISSUE THREAD

**Issue by Bala2Excel** [tomitrescak/meteor-uploads#142]
Hi 

Apologize if this is a stupid question, I used your package, It works great and I was able to download the package via the Http URL. However, I couldn't located the file in the folder? In the MongoDB I see the FileInfo collection!
Where the file gets stored? Once the user uploads the file, I need to read the file and create/ Update other Mongo Collection!
Please advice.

**Comment by tomitrescak** [comment]
By default, your files are stored in the hidden directory ".uploads" in the app directory, this can be configured. Please see the documentation.
