### ISSUE TITLE
Uploader not working on Xiaomi phones in Meteor Android

### ISSUE THREAD

**Issue by mitesh-mutha** [tomitrescak/meteor-uploads#143]
Hey,

I am working on an Android app on Meteor Cordova. I am using the package for uploading images. It works alright on my Nexus 5 device. However, it is throwing the following error on the client side - a Xiaomi phone. It seems to be originating from Template helper of buttons template. Please tell me what I can do to fix this. Let me know what additional information I can provide that might be of use.

I20150826-21:38:50.085(5.5) (android:http://meteor.local/packages/meteor.js:914) Exception in template helper: TypeError: Cannot call method 'get' of undefined
I20150826-21:38:50.085(5.5)? at Object.idle (http://meteor.local/packages/tomi_upload-jquery.js?e21323223b63581c20fdef94cc79017e915ae485:2398:58)
I20150826-21:38:50.085(5.5)? at Object.Template.buttons.helpers.idle (http://meteor.local/packages/tomi_upload-jquery.js?e21323223b63581c20fdef94cc79017e915ae485:2769:23)
I20150826-21:38:50.085(5.5)? at http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16
I20150826-21:38:50.086(5.5)? at http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16
I20150826-21:38:50.086(5.5)? at http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
I20150826-21:38:50.086(5.5)? at Function.Template._withTemplateInstanceFunc (http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
I20150826-21:38:50.086(5.5)? at http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27
I20150826-21:38:50.086(5.5)? at Object.Spacebars.call (http://meteor.local/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
I20150826-21:38:50.086(5.5)? at http://meteor.local/packages/tomi_upload-jquery.js?e21323223b63581c20fdef94cc79017e915ae485:2665:22
I20150826-21:38:50.086(5.5)? at null.<anonymous> (http://meteor.local/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2626:44)

**Comment by tomitrescak** [comment]
Device specific help is problematic as I cannot reproduce the behaviour. I do not have capacity to solve these issues, I'm sorry. The only way for you is to debug your client calls to understand what is happening. Once you isolate the bug in your scenario, please report back so I can work on fix ... or even better, do the pull request to have it done ASAP and contribute to community.

**Comment by tomitrescak** [comment]
From what I found out, new KitKat has problems with <input type="file"> so it is not related to the plugin :/
