### ISSUE TITLE
Refreshing page after upload

### ISSUE THREAD

**Issue by yudaprama** [tomitrescak/meteor-uploads#147]
I noticed that after uploading done, the page will refresh. It is by default or my mistake? No error on chrome console

**Comment by onbjerg** [comment]
What is your setup? This doesn't happen for me.

**Comment by subatomicceo** [comment]
Might be due to Meteors auto refresh.. When you run Meteor locally it rebuilds your app anytime a file is added, edited, or removed. This does NOT occur after deploying to a server. Hope this helps :)

**Comment by onbjerg** [comment]
If what @subatomicceo is the case for you @yudaprama, maybe try uploading to a different directory. Meteor ignores hidden folders. Try doing it in a directory called ``.uploads``.

**Comment by yudaprama** [comment]
Yes maybe because there are some change in client. So the server refresh automatically. I use public folder
