### ISSUE TITLE
formData not passing updated Session var

### ISSUE THREAD

**Issue by warrichrepos** [tomitrescak/meteor-uploads#148]
Hi, I'm having a problem getting formData to pass the correct data from a session variable. This is a wonderful package and this seems to be my only problem.

After my template loads, the initial value of formData 'myfolder' is set initially to nothing. When the session value changes via a select input option and I upload a file, it never uses the updated value from the session. I see from an example from above that this should work, but it does not. I'm sure I'm doing something wrong somewhere but I can't see where. If anyone could help or provide me with a clue that would be fantastic. Thanks again for the wonderful package.

[client]
Template.uploader.helpers({
   specificFormData: function() {
      
      var myfolder = Session.get('currentFolder');
     
      return {
        owner: Meteor.userId(),
        folder: myfolder        
      }
    },

[server]
if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
    
    UploadServer.init({
      tmpDir: process.env.PWD + '/.uploads/tmp',
      uploadDir: process.env.PWD + '/.uploads/',
      checkCreateDirectories: true, 

      imageVersions: {thumbnailBig: {width: 400, height: 300}, thumbnailSmall: {width: 200, height: 100}},

      getDirectory: function(fileInfo, formData) {
        
        console.log('fileInfo:', fileInfo);
        console.log('formData:', formData);
        return formData.owner + '/' + formData.folder;
      },
}

**Comment by warrichrepos** [comment]
When I look at the "context" argument in the finished callback, I see that the formData included there has the updated session value , but it is not the same value in the "getDirectory" function.

As a side note, I've also tried using reactiveVar in the Template instance and that apparently has the same behavior. 

Is it possible that the formData is not properly updating upon upload, and rather using only the initialized values? Thanks in advance.

**Comment by warrichrepos** [comment]
I still need to confirm this, but I think I found the solution from this fork for this specific problem to make the formData reactive... https://github.com/glyphing/meteor-tomi-upload-jquery

**Comment by warrichrepos** [comment]
The fork above has fixed my problem. HTH others.

**Comment by chongwang87** [comment]
+1 for Reactive variables on formData

**Comment by tomitrescak** [comment]
Guys, am a bit swamped these days. It seems that having reactive form data would be an asset. The issue is, that formdata is initialised with the jquery upload component. It would be worth to investigate if we could insert some data to it in `Uploader.startUpload`.

**Comment by tomitrescak** [comment]
@warrichrepos would you care to do a PR for your solution?

**Comment by tomitrescak** [comment]
Ok, since you guys seem like you really need this soon, I put a new verion online 2.2.0 that has the possibility to dunamically change the formData. I have also updated the documentation which reads following:

If you have several different upload controls on a page and you can execute different callbacks by passing them to the template:

```html
<template name="home">
    {{> upload_bootstrap callbacks=myCallbacks }}
</template>
```

And then pass the finished in the callback from helper

```javascript
Template.home.helpers({
  myCallbacks: function() {
    return {
        formData: function() { return { id: "232323", other: Session.get("ReactiveParam") } },
        finished: function(index, fileInfo, context) { ... },
        ...
    }
  }
})
```

I hope this help. Please close the issue if it does.

**Comment by chongwang87** [comment]
Great!

`tomi:upload-jquery v2.2.0` now working with Session and Template.instance() on formData callback

**Comment by warrichrepos** [comment]
Great news! Thank you!

**Comment by Gibigbig** [comment]
Just wanted to say thank you for making this reactive
