### ISSUE TITLE
[Question] Resizing before upload to server

### ISSUE THREAD

**Issue by SturmDrangAltaar** [tomitrescak/meteor-uploads#149]
Hi,

Is there any way, if it is even at all possible, to resize images before they are uploaded to the server using this plugin? I'm uploading from mobile devices, so data usage is of concern.

I've installed this package: https://github.com/thinksoftware/meteor-image-resize-client/
Would it be possible to integrate that functionality with meteor-uploads, or perhaps meteor-uploads already offers this functionality in some way?

Thanks!

**Comment by maksimkurb** [comment]
+1
I'd like to see some event before file sending, so I can modify files and even stop uploading event (Client-side validation for ex.)

I'd like to load Excel file, convert it to JS array and load into HandsOnTable plugin, so I don't need server-side version of plugin at all, computing should be performed on client's device.

**Comment by SturmDrangAltaar** [comment]
@tomitrescak is there anyway to hook into the change function located at https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L313 ?

**Comment by tomitrescak** [comment]
How about using `validate` callback on client? In there you can access the uploaded file.

**Comment by SturmDrangAltaar** [comment]
Thanks @tomitrescak 

In the validate callback, I'm guessing it's not yet uploaded and exists in the client only?

**Comment by tomitrescak** [comment]
That is correct. But you get access to upload context and the file itself.
On Wed, 18 Nov 2015 at 20:55, Petri <notifications@github.com> wrote:

> Thanks @tomitrescak <https://github.com/tomitrescak>
>
> In the validate callback, I'm guessing it's not yet uploaded and exists in
> the client only?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomitrescak/meteor-uploads/issues/149#issuecomment-157661747>
> .
>
-- 
~
Tomi Trescak / Researcher  tomi.trescak@gmail.com / 0487 261 213
