### ISSUE TITLE
{{> upload_bootstrap }} failed in Uploader.init

### ISSUE THREAD

**Issue by whoozle** [tomitrescak/meteor-uploads#15]
template fails with the following error:

Uncaught TypeError: Cannot set property 'queueView' of nulluploader.js:91 Uploader.initupload_bootstrap.js:3 Template.upload_bootstrap.createdtemplate.js:126 (anonymous function)view.js:206 fireCallbackstracker.js:480 Tracker.nonreactiveview.js:203 (anonymous function)view.js:414 Blaze._withCurrentView

the failed line is: this.data.queueView = new ReactiveVar([]);
where this.data is null. 

UploadServer.init was called (I checked that with console.log)

**Comment by tomitrescak** [comment]
Please post back if you will find anything, or send me some reproducible code. Thanks.

**Comment by whoozle** [comment]
i just copied from your example:
<template name="uploadFiles"><div class="container">{{>upload_bootstrap}}</div></template>
I switched to resumable/file-collections, because they better suit my needs, so cannot check it now, sorry. I'm using the latest meteor 1.0.2.1 + mrt:bootstrap. If it couldn't be reproduced on your side, you may close the issue.

**Comment by chrishill627** [comment]
Same issue here, dropzone template does not load either. Is it an issue with a meteor update?

**Comment by striletskyy** [comment]
I had the same issue, but then added `{{> upload_bootstrap multiply=yes }}` instead of `{{> upload_bootstrap }}` and it works.

**Comment by tomitrescak** [comment]
There were some issues when uploads were stored in the same collection as the one which record is displayed on the page. I have moved the state storage to the template instance instead of the data and problem seems to be fixed. Please get the latest version and report back if problem reoccurs. Beware of the slight, yet easily fixable breaking changes.
