### ISSUE TITLE
Getting ERR_FILE_NOT_FOUND on Android when upgrading to Meteor 1.2

### ISSUE THREAD

**Issue by miri-am** [tomitrescak/meteor-uploads#152]
See https://forums.meteor.com/t/err-file-not-found-in-meteor-file-upload-solutions-like-collectionfs-or-meteor-uploads-meteor-1-2-on-android/10103/1

**Comment by tomitrescak** [comment]
This was a single report of this problem, did you solve it?

**Comment by miri-am** [comment]
I did not try again with meteor-uploads but on CollectionFS the solution was adding ```App.accessRule("blob:*");```to the mobile-config.js file.
