### ISSUE TITLE
Pass values in finished from Server->Client

### ISSUE THREAD

**Issue by boxxa** [tomitrescak/meteor-uploads#158]
Great package and easy to use! Just trying to find out if its possible to pass more information from the server finished function to the client finished function that they can process in their finished() callback? I can't seem to find this anywhere.

**Comment by tomitrescak** [comment]
Nope, this information is fixed:/ covers 95% of use cases, for the rest you would have to modify the server behaviour. Explain better your use case and we'll see what can be done.

**Comment by boxxa** [comment]
Thanks for the reply. I have a separate page that outlines info on the uploaded processed file. I generate a Random.secret to use as the file name on the server. Then I want to pass that file name back to my client since I route to that once the upload and callback hits.

**Comment by nonissue** [comment]
Can you post some code? I kind of have an idea of what you're getting at, but not fully.

**Comment by tomitrescak** [comment]
@boxxa Sory for a veeery late reponse ;(
It is actually quite easy (and I guess you figured out the way).

What you can do is use a `finished` callback, in which you inject extra data to the fileInfo that is returned to client:

```javascript
UploadServer.init({
   ...
   finished(fileInfo, formFields) {
      fileInfo.extraData = "12345676";
   }
});
```

You will receive extra data to client. I will update documentation as well.
