### ISSUE TITLE
ImageMagick resize longest edge to "x"

### ISSUE THREAD

**Issue by nonissue** [tomitrescak/meteor-uploads#159]
Hey! I love meteor-uploads and all the hard work you've done, Tomas. Your active presence and support are commendable. 

One possible suggestion is to include the option for imagemagick to resize the longest edge of an image, rather than providing a strict w x h. The images I'm working with are portrait and landscape, so having to resize them to a strict w x h pixel size does not work. 

As far as I can tell, you can pass the length of the longest edge to imageMagick affixed with ">" and it will resize the image appropriately. I haven't done any tests, I just found the response with some quick searching. Does this sound like something you'd consider implementing?

**Comment by tomitrescak** [comment]
Hi, I have not tested it, but I'm pretty sure that if you only specify width and no length it will yield into your desires behaviour.

**Comment by nonissue** [comment]
With just width specified, the original image is uploaded, but other versions don't get created and no error is thrown.

**Comment by tomitrescak** [comment]
Can you get the latest version of server and let me know if it helped? I did not test it.
To set only width you need to specify height as null or 0.

**Comment by nonissue** [comment]
Quickly tested this last night and it looks like it's working! I'll do some more thorough testing early next week to verify if that's okay. Thank you so much Tomi.

**Comment by nonissue** [comment]
It appears to work with both `height:0` and `height:null`. Did you change anything? I could have sworn I tried it with `height:null` yesterday! Anyway, I think you can close this issue now. Thanks again.

**Comment by nonissue** [comment]
@tomitrescak You can close this, as far as I can tell it is resolved. Thank you.
