### ISSUE TITLE
Move to Production Server

### ISSUE THREAD

**Issue by zkschmitz** [tomitrescak/meteor-uploads#16]
Tomi,

First off, thank you for this, it is a perfect way to upload files with jQuery and is really simple. When I am on a localhost server, the code works perfectly, uploading to a .uploads folder. However, when I move it to a production server with Nginx and bundle the app, it no longer works and I cannot find the .uploads folder. It throws an 502 error on /upload as it is uploading. Do you have an idea on how to correct this? Or better yet, where to put an uploads folder on my server (running Ubuntu).

Any help is greatly appreciated!

**Comment by tomitrescak** [comment]
Sorry :/ I have no idea how to configure nginx. I have everything set up with apache.

**Comment by binarytracer** [comment]
@tomitrescak, the package works on nginx + phusion passenger environment  :+1:

**Comment by tomitrescak** [comment]
Good news! Would you care to post about possible tweaks you had to do, bumps or anything that can help others? Or did it work out of the box?

**Comment by binarytracer** [comment]
It works just out of the box!

**Comment by tomitrescak** [comment]
Thanks for confirming
