### ISSUE TITLE
More than one upload server end points

### ISSUE THREAD

**Issue by Rasof** [tomitrescak/meteor-uploads#162]
Hi ,

I'm looking to make my server accept file from many end points.

For example:
"/user/upload-image" 
"/post/upload-main-image" -> this will be handled differently by different segment of code
"/post/upload-sub-image" -> this will be handled also differently

Is it possible?

**Comment by tomitrescak** [comment]
No, the server package supports only one upload URLs. Instead, why not pass different formdata to distinguish between different content?
