### ISSUE TITLE
Uncaught TypeError: Cannot read property 'callbacks' of null

### ISSUE THREAD

**Issue by Firescar96** [tomitrescak/meteor-uploads#164]
uploader.js:281 Uncaught TypeError: Cannot read property 'callbacks' of null

I'm getting this error after following the steps for creating a custom file uploader template. It seem doesn't affect the call to `Uploader.finished` but it's still an error. I don't know if the error appears when the provided templates are used. 
The code where I'm getting this bug is here: [Flare](https://github.com/Firescar96/Flare/tree/master/node/frontend/client/submit/uploadFile)

**Comment by tomitrescak** [comment]
Hi, sorry for the lack of response. It looks good to me.. are you still having the issue?

**Comment by Firescar96** [comment]
yes, it doesn't affect anything as far as I can tell, but it's an error in the console

**Comment by nonissue** [comment]
I wonder if it's because it's a Template method in a Meteor.startup block. If you were move the finished callback to:

```javascript
Meteor.startup(function() {
    Uploader.finished = function(index, fileInfo, templateContext) {
      fileInfo.state = "new"
      JARSDB.insert(fileInfo);
    }
})
```

Does the issue still occur? I didn't have time to test.

**Comment by giggioz** [comment]
I think you just need to pass a data context to your custom template

`{{> customUpload callbacks=myCallbacks}}`

and then define `myCallbacks` in your helper.

**Comment by tomitrescak** [comment]
Is fixed in the latest release, no workaround necessary. Thanks for reporting this!

**Comment by tomitbe** [comment]
Hi tomitrescak, I have integrated custom template and passed attribute autoStart=true, but doesn't work.
 {{> customUpload autoStart=true callbacks=myCallbacks formData=keyname}}

When I use the bootstrap version, it's working fine:
{{> upload_bootstrap autoStart=true callbacks=myCallbacks formData=keyname}}

I have used the customUpload that I found on your github page: https://github.com/tomitrescak/meteor-uploads
