### ISSUE TITLE
Creates the directory as "/undefined./.uploads/tmp/"

### ISSUE THREAD

**Issue by AhmedSayed77** [tomitrescak/meteor-uploads#165]
I'm on windows, using your package inside my custom package. Obviously "process.env.PWD" returns undefined, so the directory is created outside my project given the path "/undefined./.uploads/tmp/".
I can handle this by avoiding using process.env.PWD and writing the whole path i want, but i just wanted to inform you about this issue. Great package btw.

<b>Update: </b>I tried moving the the startup.js file from inside the package to the project folder; same problem.
<b>Update: </b> Then when i tried to upload another error occured:

W20151012-10:49:09.819(2)? (STDERR) 
W20151012-10:49:09.823(2)? (STDERR) events.js:72
W20151012-10:49:09.823(2)? (STDERR)         throw er; // Unhandled 'error' event
W20151012-10:49:09.824(2)? (STDERR)               ^
W20151012-10:49:09.824(2)? (STDERR) Error: ENOENT, open '\project-root\.meteor\local\build\programs\server\undefined\.uploads\tmp\6546f2660efa021b7158a59004894b85'

**Comment by tomitrescak** [comment]
I had the same problem on windows. Unfortunatelly there is no solution (that I know of) at this stage and you have to use absolute path. You can try to experiment with `process.cwd()` nd create a relative directory but that will break if you execute your code on a differrent platform.

**Comment by tomitrescak** [comment]
If you come up with something simplere, please report back and we can make it part of the documentation. Thanks. Closing for now.
