### ISSUE TITLE
localization 

### ISSUE THREAD

**Issue by tomvolek** [tomitrescak/meteor-uploads#167]
How do I localize the text on the UI ?   I am doing  the following , but don't see any text getting translated. 

Uploader.localisation = {
            browse: "فهرست",
            cancelled: i18n("Cancelled"),
            remove: i18n("Remove"),
            upload: "Upload",
            done: i18n("Done"),
            cancel: i18n("Cancel")
        }

**Comment by tomitrescak** [comment]
That should work :/ Works fine on my side.

**Comment by tomitrescak** [comment]
Closing, for lack of response.
