### ISSUE TITLE
localisation 

### ISSUE THREAD

**Issue by tomvolek** [tomitrescak/meteor-uploads#168]
How do I localise the text on the UI ?   I am doing  the following , but don't see any text getting translated. 

Uploader.localisation = {
            browse: "فهرست",
            cancelled: i18n("Cancelled"),
            remove: i18n("Remove"),
            upload: "Upload",
            done: i18n("Done"),
            cancel: i18n("Cancel")
        }

**Comment by tomitrescak** [comment]
Duplicate of #167
