### ISSUE TITLE
upload files are not created

### ISSUE THREAD

**Issue by jolegat** [tomitrescak/meteor-uploads#170]
Hi Tom,
I am working on my first meteor project and am trying to integrate your great upload module. In my test environment (win10) the upload is working, but when I try to make it run on the server (centos) the file simply does not upload - without any warning or error message (no 305 e.g.). Everything seems to have worked fine (even the 'finished' callback is called), but the file does not appear on the server (I searched all sub folders in case that i had made a mistake defining the upload folder)... any idea?
cheers
jo

**Comment by tomitrescak** [comment]
I would check permissions on your server. Make sure that upload folder has a write permission for the correct user.

**Comment by jolegat** [comment]
That was my thought as well, so I gave all permission - no result. Strangely, after a server restart, it worked :) Thanks for your fast answer!
