### ISSUE TITLE
 FileList object  empty

### ISSUE THREAD

**Issue by ahmedrabie** [tomitrescak/meteor-uploads#171]
hi ,
  that what i am  usign    {{> upload_bootstrap callbacks=callback }}
 and 
i am try to get    FileList object      from  $(".jqUploadclass")[0].files but  result empty .

why ?
and  when  using  normal case like  
//<input type="file" class="test" >
return  object

**Comment by Koleok** [comment]
I would love to know the same

**Comment by tomitrescak** [comment]
The correct class is `jqUploadclass ` not `jqUploadclasss`. Anyway, I'm not sure if it's even accessible there. I keep the list of files in the `uploadQueue` template property. If you want to access it I advise you to create a custom template according to instructions,

**Comment by ahmedrabie** [comment]
okey but i need  it to be same  style   how to do that ?

**Comment by ahmedrabie** [comment]
it same problem with  a custom template

**Comment by Koleok** [comment]
Just a note, I was able to get at these in the following way:

```
Uploader.finished = function (index, file, context) {
        let data = context.uploadControl[0].files[0];
        console.log(data);
    }
```

Might not be the intended use but it allowed me to kick off some azure blob uploading logic from there _(using server storage as a backup only)_

**Comment by ahmedrabie** [comment]
can you chec please  the code there somthng wrong

**Comment by ahmedrabie** [comment]
thank you it's working

**Comment by tomitrescak** [comment]
@Koleok I have tested your solution and I do not have files piled in queue, and I always have only one file in the file info.

Also, you can use `context.queue` to access files that have been queued:

```javascript
// On Client
Meteor.startup(() => {
    Uploader.finished = function (index, file, context) {
        let data = context.queue;
        console.log(data[0]);
    }
}
```

**Comment by Koleok** [comment]
@tomitrescak awesome that is `context.queue` is enormously helpful!
