### ISSUE TITLE
Reactive FormData

### ISSUE THREAD

**Issue by Koleok** [tomitrescak/meteor-uploads#173]
After the first time the upload form ​_finishes_​, its `formData` property ceases to be reactive. Up until this time it works as expected, but it then seems to ​_freeze_​ at whatever value it had, even as the reactive variable `formData` is tied to is observed to be changing ​_(in both constellation and browser console)_.

**Comment by tomitrescak** [comment]
@Koleok I cannot reproduce this behaviour. I will ne a repro application or an exact description of steps in how to reproduce this. If this was not the case, it would be good if we could close this issue.

**Comment by Koleok** [comment]
@tomitrescak understood, I will try to strip out the proprietary stuff and put up a sample repo that contains the essentials that expose this issue

**Comment by OminStyle** [comment]
```callbacks``` can be used to achieve what you want.
https://github.com/tomitrescak/meteor-uploads/issues/148
