### ISSUE TITLE
403 Forbidden http://localhost:3000/upload

### ISSUE THREAD

**Issue by RamEduard** [tomitrescak/meteor-uploads#174]
Hello. My name is Ramón Serrano and i'm developing an app in meteor and added this package to upload profiles images. 

The error is that package doesn't let me upload a picture. That's what seems to happen from the console browser. Throw a 403 Forbidden error. That means I do not have permission to execute the action like client obviously. Which seems odd since I followed the steps for configuring the package, both server and client side.

I need resolve this issue please. Thanks.

**Comment by jamc92** [comment]
+1

**Comment by tomitrescak** [comment]
Please, check write premissions to the output directory.

**Comment by RamEduard** [comment]
i did chmod 777 -R .uploads
and 
chmod 777 -R app-folder

And nothing. Same issue. File is to small, 403 Forbidden error.

**Comment by tomitrescak** [comment]
Ramon, not sure how can I help. This really has something to do with the configuration of your server. Make sure that both the upload directory and the temp directory is created. LEt me know if you have resolved your issue. I just did a fresh download and test of the solution and all works as expected. If not, I will need a repro application. Thanks.
