### ISSUE TITLE
validateFile not working

### ISSUE THREAD

**Issue by slade991** [tomitrescak/meteor-uploads#176]
Hello
i try meteo-uploads and tried to set up a server side validation however it doesn't seems to work.
Here is validation code:

validateFile : function(file) {
                valids = ['image/jpeg', 'image/jpeg', 'image/png', 'image/gif'];
                if (valids.indexOf(file.type) === -1) {
                    return false;
                }
                return true;
            }

False is returned but file is uploaded anyway...

**Comment by tomitrescak** [comment]
@slade991 I have to admit, by the moronic design I was expecitng true to return in case of error. I have flipped this condition and it will be fixed in the next release. Please let me know if it works for you. I will close this for now.

**Comment by tomitrescak** [comment]
Actually, I changed my mind, I reversed the functionality and updated the documentation. 
The validate function has to return the **Description of error".
As a result, it is up to you what you want to tell the user. 

So, no error .. function returns null. Error returns description of error.
