### ISSUE TITLE
Failed: 0 Error 0 Byte

### ISSUE THREAD

**Issue by sschuchlenz** [tomitrescak/meteor-uploads#177]
I have successfully implemented your upload solution into one of our applications but for one particular user the file upload (which works for others flawlessly) fails with the error message:

`Failed: 0 Error 0 Byte`

Please advise.

**Comment by RamEduard** [comment]
+1

**Comment by tomitrescak** [comment]
I will need a repro for this. Particular cases are difficult to chase.
I have been using this solution for about 2 years now and occasionally I get 503 error when communication breaks down, unfortunatelly I did not experience your issue. I will need as much info as you can provide, from server and client logs.

**Comment by sschuchlenz** [comment]
I've found out that (at least in my case) the problem is SSL: when you have a site that is configured to be accessible via SSL and non-SSL connections, the problem is that when a user goes to https://mydomain.com `meteor.absoluteUrl()` still returns the non-SSL URL which leads to a "mixed content" warning in the browser. Since we've decided to use the `force-ssl` package the problem is solved for us but maybe you could update your package so that it does reflect this special case?

Thanks for your answer!
