### ISSUE TITLE
[Question] How can I programatically upload the files without the user have to click the upload button?

### ISSUE THREAD

**Issue by dmeneses** [tomitrescak/meteor-uploads#187]

**Comment by tomitrescak** [comment]
Just put autoStart to true. This will not render the Start button and file will start uploading automatically. Please read the documentation.

**Comment by dmeneses** [comment]
Sorry but in any place in the documentation mention the autoStart.

**Comment by AcceleratedWebSolutions** [comment]
autoStart can be added where?

**Comment by tomitrescak** [comment]
`<upload_bootstrap autostart="true" />` will do the trick. I'll have to update the documentation.

**Comment by AcceleratedWebSolutions** [comment]
Thanks, that worked like a charm!
