### ISSUE TITLE
POST http://localhost:3000/upload 503 (Service Unavailable) window meteor server

### ISSUE THREAD

**Issue by alectronic0** [tomitrescak/meteor-uploads#189]
I have been trying to use this code in my meteor app but it keep giving me a:

POST http://localhost:3000/upload 503 (Service Unavailable)

the cmd console give me this code as well

=> Exited with code: 8
=> Meteor server restarted
W20151211-14:46:02.509(0)? (STDERR)
W20151211-14:46:02.509(0)? (STDERR) events.js:72
W20151211-14:46:02.509(0)? (STDERR)         throw er; // Unhandled 'error' event
W20151211-14:46:02.509(0)? (STDERR)               ^
W20151211-14:46:02.510(0)? (STDERR) Error: ENOENT, open 'D:\Alec Meteor Workspace\meteor-Uploads\.meteor\local\build\programs\server\undefined\.uploads\tmp\40a5d2a0263323002af504b4e5cefc03'

Can someone help me understand what I am doing wrong I followed all the code in the readme with no luck.

**Comment by steffenrusch** [comment]
Hi alectronic0,
I saw the same after the installation.
I just changed one thing in server/init.js:  

tmpDir:  '/tmp/uploads/tmp',
uploadDir: '/tmp/uploads/',

After that it works perfect.

If You see this after the start - it works perfect:
Created directory: /tmp/uploads/
Created directory: /tmp/uploads/tmp/

**Comment by sho-87** [comment]
I'm seeing a similar problem. I tried add /tmp/ to the beginning of the paths and I see the following in the console:

Created directory: /undefined/tmp/
Created directory: /undefined/tmp/uploads/
Created directory: /undefined/tmp/uploads/tmp/

I'm not sure where the undefined is coming from

The full error looks something like this:

`Error: ENOENT, open 'D:\Dropbox\Programming\homebrew-compute-server\.meteor\local\build\programs\server\undefined\tmp\uploads\tmp\5e0a7e8bedd068a1bfdf09f5f66ceb0e'`

It looks like its trying to create the upload directories inside the .meteor folder rather than the base project directory

I've tried specifying a full absolute path for both tmpDir and uploadDir but again, it tries to create those deep within the .meteor directory

**Comment by sho-87** [comment]
This seems to be a problem even if I don't define a custom template, and instead just use the simple starter code:
```
<template name="yourTemplate">
    {{> upload_bootstrap }}
</template>
```

**Comment by katopz** [comment]
All windows should hit this issue, do try...
```js
    var baseDir = process.env.PWD ? process.env.PWD + "/.uploads" : "/uploads";

    UploadServer.init({
        tmpDir: baseDir + '/tmp',
        uploadDir: baseDir,
        checkCreateDirectories: true,
        getDirectory: function (fileInfo, formData) {
            if (formData && formData.directoryName != null) {
                return formData.directoryName;
            }
            return "";
        },
        getFileName: function (fileInfo, formData) {
            // to prevent unicode file name problem
            var fileName = fileInfo.name;
            var extensions = fileName.split('.');
            var extension = extensions[extensions.length - 1];

            // prevent duplicated file name
            var stamp = new Date().valueOf();
            fileName = stamp + "_" + base64.encode(fileName) + '.' + extension; // Filename with extension

            if (formData && formData.prefix != null) {
                return formData.prefix + '_' + fileName;
            }
            return fileName;
        },
        finished: function (fileInfo, formData) {
            if (formData && formData._id != null) {
                Items.update({_id: formData._id}, {$push: {uploads: fileInfo}});
            }
        }
    });
```

It's kinda old, I'm not sure it still work against current version. But this should get you an idea.
PS : you can ignore `getDirectory` `getFileName` `finished` which is not related.

Cheers

**Comment by tdhz77** [comment]
I get this error on Ubuntu 14.04. I've manually created the folders and set dir to tmp. App works fine in testing, but fails in production.

Any help on this?

events.js:72
        throw er; // Unhandled 'error' event
              ^
 >>Error: EACCES, open '/opt/FT/.uploads/tmp/00e101d4f56fbe4768c641ac0cc713e3'
 >>error: Forever detected script exited with code: 8
 >>error: Script restart attempt #2
 >>Custom upload url setup to: /upload
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser

**Comment by tomitrescak** [comment]
Guys, it's always an access issue. Make sure `meteoruser` has write access to these folders.

**Comment by iFloyd12** [comment]
how?

**Comment by tdhz77** [comment]
sudo chmod 755 .uploads
