### ISSUE TITLE
Clientside 'multiple' parameter not taken into account

### ISSUE THREAD

**Issue by spikey82** [tomitrescak/meteor-uploads#19]
Hi, 

When I set the 'multiple' parameter to false within the bootstrap template, the HTML output always renders multiple=true. Looking at the template source:

    <div class="btn btn-primary btn-file upload-control">
        Browse&hellip;
        <input type="file" class="jqUploadclass" multiple="true" data-content-category="{{ contentType }}" data-form-data='{{ submitData }}' accept="{{ fileTypes }}">
    </div>

Seems an easy fix to incorporate multiple="{{multiple}}"

For now, you can also fix this clientside using jQuery:

```javascript
Template.NAME.rendered = function() {
  //set multiple uploads to false, yet bug in template...
  $(".jqUploadclass").prop('multiple',false);
};
```

**Comment by tomitrescak** [comment]
Wouter

Thanks a lot for the creative feedback! Would you be able to do a quick PR?
If you have more ideas I can even give you full access.

Thanks

Tomas

**Comment by tomitrescak** [comment]
Fixed in tomitrescak/meteor-tomi-upload-jquery@e53eab153f2bb7ccea1ac354660dd9b4fff1aab4
