### ISSUE TITLE
Resized thumbnails not display, throwing 404

### ISSUE THREAD

**Issue by nonissue** [tomitrescak/meteor-uploads#191]
I have my meteor-upload server set to generate thumbnails when an image is uploaded. In my finished callback for meteor-upload-server (in init), it calls a method which generates an array of objects with each size of thumbnail for the image and a corresponding url, and then inserts the image into an image mongo collection. 

I have a cursor clientside set to display the image thumbnail on the same page as my drop zone. However, when an image is uploaded and the document is inserted into the image collection, it appears client side as a broken image, regardless of how many times I refresh. If I visit the url of the image directly, I get a "404 image not found" message, but if I refresh while on the direct url (http://localhost:3000/uploads/testpost/200/image.jpg) of the image, it appears, and then it will appear on my site when I go back.

The original files I upload display with no problem, so I assume this is a bug with the 404 fs.lstat method and imagemagick? If I set a meteor sleep server side, it resolves the issue, but is not an ideal solution. Is there a way to tie into a callback after imagemagick finishes resizing?

**Comment by nonissue** [comment]
Minor update: if I set cacheTime to zero, after a refresh the image appears, so it is at least causing part of the problem. It would still be nice to have a hook for when imageMagick is done resizing and the thumbnails are created

**Comment by Helika0n** [comment]
I've got the same issue using the standard methods of meteor-upload.

(using imageVersions). Uploading multiple files, generally for the last one, the thumbnail will not show up until I force a cache refresh

**Comment by tomitrescak** [comment]
Guys, just add a new timestamp after the file name and you have no issue. Of course, if you have caching enabled the browser will use the cached version.

Upload it as file.jpg?temp and then remove the ?temp once you are done (make sure to remove this suffix on the server as well). This will force browser to take a fresh copy of your image.

**Comment by vinzenzweber** [comment]
@tomitrescak your tip saved my day ;)

```
Template.uploader.helpers({
  documents: function() {
    return Documents.find({}, {
      sort: {
        createdAt: -1
      },
      transform: function(doc) {
        doc.thumbnail = doc.thumbnail + '?' + Random.id();
        return doc;
      }
    });
  }
});
```
