### ISSUE TITLE
Read file data before upload

### ISSUE THREAD

**Issue by odesey** [tomitrescak/meteor-uploads#193]
Is it possible to access the file before the user uploads it? Lets say that the user is uploading an ```.mp3``` or a ```.epub``` file and I would like to display the meta-data about the file prior to uploading it. Is this possible?

Thanks for the great package, from ```meteor install ``` to uploaded files literally took less than 2 minutes!

**Comment by tomitrescak** [comment]
Sorry for a very late reply. You have access to the file in the validate callback, as according to the documentation. This gives you access to the fileInfo coming from the input conttrol.
