### ISSUE TITLE
Clearing form data on link click

### ISSUE THREAD

**Issue by sho-87** [tomitrescak/meteor-uploads#194]
I have a test webapp (http://meteorpad.com/pad/ckgN6GL4msQn4Ms5h/Jobs) where links in the nav menu call up different documents from a collection and display the data

Part of the data display is an upload section. When a link is clicked, the id of that document is stored in a session variable. This then gets passed as id in formData, so that the uploader can create a directory with the same name as the document id. Files uploaded for that document then get stored in that specific folder

This works for the first link that I click. Files get uploaded to the subdirectory bearing its name. However, when I click a new link, any files I upload get uploaded to the first documents directory

I believe this is because the form does not get reloaded, therefore formData still has the id of the first clicked document link.

With this sort of setup, how do I essentially reset the form data whenever a link is clicked, so that it is always passing the latest id, and not the first one?

**Comment by OminStyle** [comment]
https://stackoverflow.com/questions/34457879/
