### ISSUE TITLE
Uncaught Error: No such template: dropzone

### ISSUE THREAD

**Issue by berkg** [tomitrescak/meteor-uploads#20]
clone this project and run in meteor but this error in chrome console

Uncaught Error: No such template: dropzone

**Comment by tomitrescak** [comment]
Please try with the new version and report back if problem reoccurs. Yet, this should not even happen with the previous version.

**Comment by JogoShugh** [comment]
Same thing for me just now.

**Comment by JogoShugh** [comment]
Nevermind, I think it's because I didn't install the jquery package.
