### ISSUE TITLE
my template automatically refreshing after upload

### ISSUE THREAD

**Issue by pvtulsiram538** [tomitrescak/meteor-uploads#200]
Hi ,
 My template automatically refreshing after upload  .I used following code

 <div class="col-xs-6">
              {{> upload_bootstrap fileTypes='.jpg' multiple=true  callbacks=myCallbacks}}
                </div>

and i write my callback is
myCallbacks: function() {
   
    return {
      
        finished: function(index, fileInfo, data) {
        // console.log("FileInfo--------"+fileInfo.status);
        console.log("campaignId--in image helper--------"+currentCampaignId);  
       //  var campaignObj=currentCampaignId;
                  addImageDetails(fileInfo, currentCampaignId,function(result) {
                if (result) {
                    console.log("image record------"+result);
                     }
                     else
                        alertify.alert("Failed");
            });
    
     }
       
    }
  }

**Comment by tomitrescak** [comment]
Make sure you are not uploading to any meteor directory e.g. public

**Comment by yoepus** [comment]
Thanks @tomitrescak I just had the same issue and this solved it.

**Comment by pvtulsiram538** [comment]
HI  tomitrescak  ,

Thank you so much . Now its working fine but how could i display the files in template . And if i store  files in side my application .it may reduce performance of my server how could i  solve it .Can you please help me out 
 
Thanks
