### ISSUE TITLE
Unknown Path - 

### ISSUE THREAD

**Issue by tdhz77** [tomitrescak/meteor-uploads#201]
tmpDir: process.env.PWD + '/upload/tmp',
		  uploadDir: process.env.PWD + '/upload/',
		  uploadUrl: "/financialtrack/upload",
		  checkCreateDirectories: true,

I'm trying to get this to work in production. It will work in staging. 
 I deploy to 192.168.1.100/financialtrack in production, but not in staging.
When I upload something I get 404 unknown path.
This doesn't happen when I'm on staging (staging is deployed to just localhost/. So, I'm trying to figure out how to fix this problem. It's a route issue or maybe permissions on the server?

Any help?

**Comment by tdhz77** [comment]
Yes, when I check the route It looks like the uploader is trying to post to root.com/upload.
I have set the uploadUrl and path, but not having much luck here.

I have also set up FlowRouter rules regarding the old path and new path, but I'm afraid that doesn't work as well.

Any help on this?

**Comment by tomitrescak** [comment]
I was out for a month, I hope you solved it. According to documentationyou can specify an absolute path.
