### ISSUE TITLE
Start upload manually

### ISSUE THREAD

**Issue by miclaus** [tomitrescak/meteor-uploads#203]
Is there any way I can trigger the Uploader to start uploading ? As such:
```coffee
'change #picture_input': (event) ->
  Uploader.startUpload()
```
The markup:
```html
<form method="POST" enctype="multipart/form-data">
    <input
        id="picture_input"
	    style="visibility:hidden"
	    type="file"
	    data-form-data='{{ submitData }}'
	    accept="image/*"
    >
</form>
```
Thanks !

**Comment by tomitrescak** [comment]
The easiest way, as asked many times in this forum ;) is to use jquery action to trigger the button click.

**Comment by mkpazon** [comment]
It would be nice if there is a `Uploader.startUpload()` to allow more flexibility. For example, store something in the database and when successful upload the image with a name based on the object saved in the db.
