### ISSUE TITLE
How can I enable autoUpload ?

### ISSUE THREAD

**Issue by freaker2k7** [tomitrescak/meteor-uploads#204]
If the package uses [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload/wiki/Options), so how can I enable the [autoUpload](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#autoupload) option ?

Thank you ^_^

**Comment by tomitrescak** [comment]
This is in the documentation, you set autostart to true.
