### ISSUE TITLE
How to Remove/Delete File from Disk Once Removed from Collection?

### ISSUE THREAD

**Issue by newterminator** [tomitrescak/meteor-uploads#21]
Hi,
I wanted to ask that how could I remove a file from disk (from the upload folder) once it has been deleted from the collection. 
I presume that the code will be server side meteor code, but I don't know where to start. So please if someone could help with this issue.

**Comment by tomitrescak** [comment]
You have to use the `fs` package.
Make sure you create safe file path so that users won't attempt to delete the file.
Preferably don't even send paths but ids of records that point to the file path.

```javascript
var fs = Npm.require('fs');
var uploadDir = 'your/upload/dir'

Meteor.methods({
  deleteFile: function(path) {
    // TODO: make safe path
    fs.unlinkSync(options.uploadDir + path);
  }
})

```

**Comment by newterminator** [comment]
Hi @tomitrescak (Tomas) I wanted to thank you for your response and also for the immense, quality work that you have put towards this package. 

I am just a novice in meteor usage. So I wanted to ask that when you mentioned the 'fs' package did you mean the cfs package found here: https://atmospherejs.com/cfs/standard-packages

If what I found is incorrect could you please direct me to the correct one.

**Comment by tomitrescak** [comment]
Hi tthanks for the kind words. The new version supports file deletion natively in the upload server. Please see following [example](https://github.com/tomitrescak/meteor-uploads/blob/master/server/methods.js#L1-L13).

**Comment by newterminator** [comment]
Hi @tomitrescak, Thank you for your quick response on the matter. I got so excited to use the new feature. 

I updated Meteor to the latest version 1.0.3.1 which automatically updated all packages for me. So I got the latest package - tomi:upload-server version 1.0.3 (and) tomi:upload-jquery version 2.0.0. When I went to try out the code for the deletion Meteor throws an error at this line: UploadServer.delete(upload.path); 
In chrome, inspection tells me: "ReferenceError: UploadServer is not defined".

I tried removing and then adding both the packages again but still the issue prevails...

**Comment by tomitrescak** [comment]
That's a bit weird, since the deletion is done on server, so chrome has
nothing to do with it:/ areyou saying that this happens in the demo
application ?

**Comment by newterminator** [comment]
Hi @tomitrescak the demo application caused an error as well. I am attaching the image for that.
![erroronupload](https://cloud.githubusercontent.com/assets/5087437/5881742/35bff566-a311-11e4-8cba-342d7f34ee46.jpg)

And the second image is for the error that I receive when trying to delete the file on disk, using the latest version of the package.
![uploader_error](https://cloud.githubusercontent.com/assets/5087437/5882976/4e6a73ba-a31c-11e4-9c41-35b31e7c9acd.jpg)

**Comment by tomitrescak** [comment]
Hi, As I wrote in the Troubleshooting part of the documentation, make sure
the server console log is clean and disable all debugging tools on client,
just like the one I see on your screenshot.

**Comment by tomitrescak** [comment]
And the second error ... Are you calling the method on client? That will
never work, it has to be called on server.

**Comment by newterminator** [comment]
Hi @tomitrescak for the second error I am calling the method on the server. Here is the code for the function that calls on UploadServer and produces the error:
    Meteor.methods({
          deleteUploads: function(toBeDeleted) {
      for(var i = 0; i<toBeDeleted.length; i++) {
          var upload = Uploads.findOne({_id: toBeDeleted[i]});
          UploadServer.delete(upload.path);
          Uploads.remove({_id: toBeDeleted[i]});
      }
  }
});

**Comment by tomitrescak** [comment]
If you are calling it in server, how come that you see the error in the
client console?

**Comment by newterminator** [comment]
Hi @tomitrescak,
I am attaching the image of the error being shown in the terminal window, as Meteor throws the error while trying to call the delete method. I highlighted the methods error and the file path of the methods.js file (which shows that the file is in the server folder) where the deleteUploads is being called.

![upload_error](https://cloud.githubusercontent.com/assets/5087437/5935095/1caca532-a6a5-11e4-955b-a0a94e019cd8.jpg)

**Comment by tomitrescak** [comment]
That's weird, are you sure you have the latest version? Can you post here your .meteor/.versions file please? Thanks.

**Comment by newterminator** [comment]
Hi @tomitrescak, I am attaching the versions file as requested. I marked the section with red showing the packages' version. 
![versions_file](https://cloud.githubusercontent.com/assets/5087437/5954644/565d62d0-a768-11e4-95dc-47d3162fb930.jpg)

Today once again I created my app from scratch, and following the same procedure, I got inserting uploads working and saving on disk. However, interestingly when I called the 'delete' method as in the previous times, I did not get an error as in the image from my last comment above. 

But at the same time the file on disk did not get deleted. 

So to check my curiosity, I downloaded the master demo app once again today, and ran it without touching any line of code and I got the same error as in my last comment above: 
![demo_app_error](https://cloud.githubusercontent.com/assets/5087437/5954790/3b82ef50-a76a-11e4-9711-ba50c9f2906e.jpg)

Now when I went in to the terminal to see the mongodb for the demo app, this is what I saw (other fields are getting saved fine, but path is undefined):
![path_undefined](https://cloud.githubusercontent.com/assets/5087437/5954839/e5df171c-a76a-11e4-8d5a-54467fd3ca35.jpg)

To compare when I saw the mongodb in my app, this is what I saw: (path field contains basically the file name including the slash): 
![path_file_name](https://cloud.githubusercontent.com/assets/5087437/5954929/a330b4ec-a76b-11e4-92e9-50c91a16b59c.jpg)

So these are my findings Tomas. 

I wanted to ask you that you had mentioned in your second post to use the 'fs' package - how can I add that package to the meteor app to further test this delete feature.

**Comment by tomitrescak** [comment]
Well, you need server version 1.1.0 in order to be able to delete files, you are using version1.0.3,  just run meteor update on that and all shall work!

**Comment by tomitrescak** [comment]
That was my bad, I just found out that version 1.1.0 was not published, did it now. Just run meteor update. I am terribly sorry for your issues :/

**Comment by newterminator** [comment]
Hi @tomitrescak,

Sorry Tomas didn't get back to your messages as I away from work for the weekend. I am glad you recognized where the problem was and rectified it. 

And as a person working on code as well, I realize the complexities one has to deal with, so don't worry about the issue. I will like to thank you though for your work on this package to make it as simple as possible to use. 

So I did use the new updated package and HURRAY HURRAY the file was successfully deleted from the disk.
