### ISSUE TITLE
Encrypt images

### ISSUE THREAD

**Issue by MatFluor** [tomitrescak/meteor-uploads#211]
Hi there,

is there a way (or on a roadmap) to encrypt images (and possibly their thumbnails)? This would be handy if you want to guarantee the security/privacy of a users data and soociated images.

MongoDB entries can be encrypted client-side with e.g. this:
(https://medium.com/meteor-js/client-side-aes-encryption-with-meteor-3be8d645fc12#.97818budt)

Greets

**Comment by tomitrescak** [comment]
There is no plan to implement this functionality, sorry :/
