### ISSUE TITLE
502 bad gateway from nginx due to Imagemagick

### ISSUE THREAD

**Issue by parthibanloganathan** [tomitrescak/meteor-uploads#212]
I've read https://github.com/tomitrescak/meteor-uploads/issues/108 and https://github.com/tomitrescak/meteor-uploads/issues/40 already. 

I am receiving a 502 bad gateway response. I believe it's due to Imagemagick. When I remove the `imageVersions` piece of code which requires Imagemagick, the error disappears. I've already run `sudo apt-get install imagemagick` and `npm install -g imagemagick` on my Ubuntu DigitalOcean box. Have also tried building Imagemagick from source.

Permissions seem to be fine. Ran `chmod 777` on `/opt/myapp/current/bundle/.uploads` just to be safe and can access images there.

Tested Imagemagick by running `convert` on a file and it worked fine, so Imagemagick seems to be properly installed. Any recommendations on how to fix this issue?

**Comment by tomitrescak** [comment]
Does everything work without imagemagick?

**Comment by parthibanloganathan** [comment]
Yes, it does.

**Comment by shaneBen23** [comment]
If you are using mupx to deploy your app, try installing imagemagick (apt-get install imagemagick) in your apps docker container.

I was having the same problem and this worked for me.

**Comment by greenwolfe** [comment]
Just got this working, but I have a question.  Will I have to re-install imagemagick every time I re-deploy with mupx?  If so, and someone has automated that process already, would you be willing to share?

**Comment by tomitrescak** [comment]
If you use mupx ... then you need to search for container that has imagemagick preinstalled. Consider using the new mup with a custom container.

**Comment by greenwolfe** [comment]
I wrote a bash shell that installs imagemagick right after install, and its working, but a custom image would be better.  I'll look into it.  I can't use the new mup because I've already decided to stick with meteor@1.1 until things settle down a little more.  I just don't have the time to keep rewriting every time there are major changes.
