### ISSUE TITLE
Startup error with 1.3-beta.11

### ISSUE THREAD

**Issue by Maxximus007** [tomitrescak/meteor-uploads#214]
Server startup fails with Meteor 1.3-beta.11

**Comment by batjko** [comment]
Could you add some details, such as the error stack for example?

**Comment by Maxximus007** [comment]
To explain a little: trying to run manuel/Phonebook example with 1.3 (currently B.12). Perhaps tis can be of help:
`jquery.iframe-transport.js:21Uncaught TypeError: Cannot read property 'jQuery' of undefinedcounter @ jquery.iframe-transport.js:21(anonymous function) @ jquery.iframe-transport.js:23(anonymous function) @ tomi_upload-jquery.js?hash=b1bbadf…:829(anonymous function) @ tomi_upload-jquery.js?hash=b1bbadf…:3294
global-imports.js?hash=04fba9b…:4 Uncaught TypeError: Cannot read property 'Uploader' of undefined(anonymous function) @ global-imports.js?hash=04fba9b…:4`

**Comment by FBRTMaka** [comment]
+1

**Comment by tomitrescak** [comment]
This has been solved already, did you update your plugin? It's the client.

**Comment by FBRTMaka** [comment]
Thanks @tomitrescak , I did and it works great!
