### ISSUE TITLE
validateRequest not sending callback to client

### ISSUE THREAD

**Issue by FBRTMaka** [tomitrescak/meteor-uploads#218]
I'm able to get the req headers in the validateRequest callback, but then it goes no where.  The client just hangs at 0% completed and there doesn't seem to be a proper error sent back in order to handle the request validation.

**Comment by tomitrescak** [comment]
You need to return the description of the error if there is an error, then the error will be displayed in the Progress bar:

```
validateRequest: function(request) {
      return "This is error message";
    }
```

leads to:

![Uploading Screen Shot 2016-03-15 at 18.56.45.png…]()

**Comment by FBRTMaka** [comment]
Thanks Tomi, I figured out that the problem was what I was trying to do during the callback -- I am checking the md5 (send in the request header) against the md5 of every file in the local system before upload.

Doing this on a small files works fine, but my files are up to 5 GB . . . I'm sure the client won't wait that long for the callback.

Thanks for your response!

**Comment by c316** [comment]
I am also seeing this

**Comment by c316** [comment]
NVM
