### ISSUE TITLE
503 (Service Unavailable)

### ISSUE THREAD

**Issue by striletskyy** [tomitrescak/meteor-uploads#22]
Hello,

While I am uploading, I get error:

![screen shot 2015-01-20 at 12 26 47 pm](https://cloud.githubusercontent.com/assets/5245787/5815638/de7d9b50-a09f-11e4-9a97-40ffd41271a2.png)

My html code:
```
<div class='import'>
  {{> upload_bootstrap multiply=yes }}
</div>
```

**Comment by provolot** [comment]
I just had this problem, and it turned out to be a path issue for the UploadServer.init params: either the directories were wrongly configured, and/or didn't exist. This was what I used successfullyL
```
tmpDir: process.env.PWD + '/public/uploads/tmp'                          
uploadDir: process.env.PWD + '/public/uploads/'
```

**Comment by striletskyy** [comment]
It doesn't work for me. I used 

```
UploadServer.init({
    tmpDir: process.env.PWD + '/public/uploads/tmp',
    uploadDir: process.env.PWD + '/public/uploads/',
    getDirectory: function(file, formData) {
      // create a sub-directory in the uploadDir based on the content type (e.g. 'images')
      return formData.contentType;
    },
    finished: function(file, folder, formFields) {
      // perform a disk operation
    }
  });
```

**Comment by striletskyy** [comment]
It works, just restart few times. But, why after uploaded the page refresh?

**Comment by tomitrescak** [comment]
Hi, I have bumped into this problem with Firebug. When it's on and used for a longer time it will lead to 503 error and mostly for larger files. If you turn off firebug and any kind of JS debug tool the problem should disappear.

**Comment by tomitrescak** [comment]
I will close this issue, please reopen if necessary. I will also update troubleshooting docs.

**Comment by conorstrejcek** [comment]
I am having this issue as well, but it does not seem to be connected to Firebug or any other debug tool.

I get the same 503 error as @striletskyy , but on the server side I get: `TypeError: Converting circular structure to JSON`.

An object appears in the `.uploads/` folder, but it doesn't seem to be accessible.

The full trace for the `TypeError` looks like:

    /Users/<username>/dev/<appName>/.meteor/local/build/programs/server/packages/tomi_upload-server.js:146
    W20150202-08:15:48.459(-6)? (STDERR)           res.end(JSON.stringify(result));                                    
    W20150202-08:15:48.459(-6)? (STDERR)                        ^
    W20150202-08:15:48.459(-6)? (STDERR) TypeError: Converting circular structure to JSON
    W20150202-08:15:48.459(-6)? (STDERR)     at Object.stringify (native)
    W20150202-08:15:48.459(-6)? (STDERR)     at [object Object].handleResult [as callback] (packages/tomi:upload-server/upload_server.js:123:1)
    W20150202-08:15:48.460(-6)? (STDERR)     at IncomingForm.finish (packages/tomi:upload-server/upload_server.js:231:1)
    W20150202-08:15:48.461(-6)? (STDERR)     at IncomingForm.emit (events.js:92:17)
    W20150202-08:15:48.461(-6)? (STDERR)     at IncomingForm._maybeEnd (/Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:551:8)
    W20150202-08:15:48.461(-6)? (STDERR)     at /Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:229:12
    W20150202-08:15:48.461(-6)? (STDERR)     at WriteStream.<anonymous> (/Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/file.js:70:5)
    W20150202-08:15:48.461(-6)? (STDERR)     at WriteStream.g (events.js:180:16)
    W20150202-08:15:48.462(-6)? (STDERR)     at WriteStream.emit (events.js:117:20)
    W20150202-08:15:48.462(-6)? (STDERR)     at finishMaybe (_stream_writable.js:359:12)
    W20150202-08:15:48.462(-6)? (STDERR)     at afterWrite (_stream_writable.js:279:5)

**Comment by Xample** [comment]
Same problem here, trying to use meteor-uploads-server with https://atmospherejs.com/danialfarid/ng-file-upload (I am using angularjs as the gui)
Going to
http://localhost:5000/upload/ gives me ```Access denied````

However, I can upload from the ```meteor-uploads``` blaze template.

Here is the failing request's header (using ng-file-upload):
```yaml
General
Remote Address:127.0.0.1:5000
Request URL:http://localhost:5000/upload
Request Method:POST
Status Code:503 Service Unavailable
Response Headers
Connection:keep-alive
Content-Type:text/plain
Date:Wed, 02 Sep 2015 09:46:09 GMT
Transfer-Encoding:chunked
Request Headers
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Connection:keep-alive
Content-Length:182602
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryDUqFXLOrRPi6VsVA
Cookie:_ga=GA1.1.254208428.1419424835; __atuvc=38%7C25; __atssc=facebook%3B1
Host:localhost:5000
Origin:http://localhost:5000
Referer:http://localhost:5000/app/videos/gwGir27zcLq3CgfX7
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
Request Payload
------WebKitFormBoundaryDUqFXLOrRPi6VsVA
Content-Disposition: form-data; name="file"; filename="SmartVideos sync process.pdf"
Content-Type: application/pdf


------WebKitFormBoundaryDUqFXLOrRPi6VsVA-````
````
And the successful one (using meteor-uploads):
````yaml
General
Remote Address:127.0.0.1:5000
Request URL:http://localhost:5000/upload
Request Method:POST
Status Code:200 OK
Response Headers
access-control-allow-headers:Content-Type, Content-Range, Content-Disposition
access-control-allow-methods:OPTIONS, HEAD, GET, POST, PUT, DELETE
access-control-allow-origin:*
cache-control:public, max-age=100
connection:keep-alive
date:Wed, 02 Sep 2015 09:46:43 GMT
transfer-encoding:chunked
vary:Accept-Encoding
Request Headers
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Connection:keep-alive
Content-Length:182802
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarywTHAxfpBgtdY6aOx
Cookie:_ga=GA1.1.254208428.1419424835; __atuvc=38%7C25; __atssc=facebook%3B1
Host:localhost:5000
Origin:http://localhost:5000
Referer:http://localhost:5000/app/videos/iyJXYQxQgbaNux4FW
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
------WebKitFormBoundarywTHAxfpBgtdY6aOx
Content-Disposition: form-data; name="type"

files
------WebKitFormBoundarywTHAxfpBgtdY6aOx
Content-Disposition: form-data; name="directory"

files
------WebKitFormBoundarywTHAxfpBgtdY6aOx
Content-Disposition: form-data; name="files[]"; filename="SmartVideos sync process.pdf"
Content-Type: application/pdf


------WebKitFormBoundarywTHAxfpBgtdY6aOx--```
```

Can this be related to the Request Payload ?
