### ISSUE TITLE
Check user state before uploading

### ISSUE THREAD

**Issue by phucnv206** [tomitrescak/meteor-uploads#228]
Hi team,
Is there any way to check if user not logged in?
I used this.userId and Meteor.userId() but it not work both.
Thanks.

**Comment by nick-preda** [comment]
Hi,

If a user is logged in, Meteor.userId() returns a unique ID, otherwise it returns undefined ;)

**Comment by tomitrescak** [comment]
@phucnv206 .. not on server as the server is not running in the Meteor fiber I'm affraid.
