### ISSUE TITLE
"Finished" function is different between server and client

### ISSUE THREAD

**Issue by rafaelfaria** [tomitrescak/meteor-uploads#23]
I'm trying to create a logic to change the filename once it uploads the files and i'm having a conflict between names from the server and the client.

If i have as suggested on the documentation, when i change the filename on my UploadServer, when it finishes, the server knows what is the correct name, but the client doesnt, still gets the original name, therefore it's quite hard to get the image that has been uploaded.

Any suggestion?

```
if (Meteor.isClient) {
	Uploader.finished = function(index, file) {

		if (!Session.get("UploadedFiles")) {
			Session.set("UploadedFiles", []);
		}

		var files = Session.get("UploadedFiles");
		files.push(file);

		Session.set("UploadedFiles", files);

		// for reactivity you can write to the collection
		// e.g. SomeCollection.insert({path: folder + '/' + file});
		console.log('Write to database: ' + file.name);
	}		
}
if (Meteor.isServer) {
	Meteor.startup(function() {

		UploadServer.init({
			tmpDir			: process.env.PWD + '/.uploads/tmp',
			uploadDir		: process.env.PWD + '/.uploads/',
			uploadUrl		: '/uploads/',
			//imageVersions	: { thumbnailBig: {width: 400, height: 300}, thumbnailSmall: {width: 200, height: 100} },
			getFileName		: function(file, formData) {
				return new Date().getTime() + Random.id() + file;
			},
			finished: function(file, folder, formFields) {
				console.log('Write to database: ' + folder + '/' + file);
			}
		});

	});
}
```

and

**Comment by rafaelfaria** [comment]
Answering my own question.

the **"name"** property of the file hasnt changed, although it's possible to extract the new name from the **"path"** property.

**Comment by tomitrescak** [comment]
Rafa, new version is coming where all this is debugged.
I have used the uploader in a larger scale project and I'm preparing a fresh new version with support for semanticui as well.

**Comment by rafaelfaria** [comment]
Nice. Just saw it come up today. I will try tonite. 

I'm building a media library manager, similar to the one on wordpress for my project. Hopefully i can build in a way that i can share once it's done. It's my first project in meteor so I can't promise much, but your module is pretty helpful.

Thanks for it.
