### ISSUE TITLE
UploadUrl per upload form ?

### ISSUE THREAD

**Issue by rXp** [tomitrescak/meteor-uploads#230]
Hello,

I'm looking for a way to have multiple different forms on my website and they must upload at different places.
Can I init several instances of Uploader ? If I can, how can I tell each form that I want them to POST at specific URL ?

Thanks for the help,

rXp

**Comment by tomitrescak** [comment]
The only way I can see this work is to set the Uploader.uploadUrl in one of the callbacks. Should be pretty straightforward.
