### ISSUE TITLE
Doesn't work after Deploying to Ubuntu (Meteor 1.3.2.4) 

### ISSUE THREAD

**Issue by aalhaimi** [tomitrescak/meteor-uploads#232]
I've tested the package.. It works ok via localhost on osx. I deployed it using MUP to Ubuntu server and nodeVersion 0.10.43.. It deployed nicely, but the upload feature doesn't work there. Any solution?

**Comment by dmitry-sher** [comment]
It's very hot question for me also, i was going to deploy my builds to Ubuntu 14.04 with nginx .. can you please provide more details or ready to mess with Git repo, perhaps?

**Comment by c316** [comment]
Make sure you check that the meteoruser has permission on the upload folder
and any subfolders. That was the problem for me

**Comment by aalhaimi** [comment]
yes, I'm guessing that's the problem.. Thanks guys! I just need to figure out how to assign 755 permission to meteoruser.

**Comment by dmitry-sher** [comment]
sudo chown -R user:group /path/to/start/from

**Comment by aalhaimi** [comment]
awesome, thanks!

**Comment by dmitry-sher** [comment]
```sudo chmod -R 755 /path/to/start/from```

and of course if you are in a group and have proper permissions, it can also work without sudo

**Comment by aalhaimi** [comment]
Just a quick update:  It turned out a permission issue. To anyone who might face a similar issue, make sure that folder ".uploads" and sub-folder "tmp" on the server owned by "meteoruser" and have 755 write permissions. If you deployed the app using Meteor-Up, then you'll probably find the ".uploads" folder at "/opt/[app-name]/". 

Solution: 
1- ssh into the server
2- cd to the app directory
3- change ownership of ".uploads" folder and the "tmp" sub-folder. For example using this code: `sudo chown meteoruser .uploads`
4- change permission of these folders to 755. For example using this code: `sudo chmod -R 755 .uploads`


This solution will also solve similar issues reported by others:
http://stackoverflow.com/questions/29470085/err-connection-refused-using-meteor-uploads
https://github.com/tomitrescak/meteor-uploads/issues/145
https://github.com/tomitrescak/meteor-uploads/issues/110
