### ISSUE TITLE
imageVersions returning errors

### ISSUE THREAD

**Issue by rafaelfaria** [tomitrescak/meteor-uploads#24]
I'm trying to generate different versions of my image using the **imageVersions** property but i'm getting an error.

```
imageVersions	: { thumbnailBig: {width: 400, height: 300}, thumbnailSmall: {width: 200, height: 100} },
```

```
W20150122-00:31:00.040(11)? (STDERR)
W20150122-00:31:00.041(11)? (STDERR) events.js:72
W20150122-00:31:00.041(11)? (STDERR)         throw er; // Unhandled 'error' event
W20150122-00:31:00.041(11)? (STDERR)               ^
W20150122-00:31:00.041(11)? (STDERR) Error: spawn ENOENT
W20150122-00:31:00.041(11)? (STDERR)     at errnoException (child_process.js:1001:11)
W20150122-00:31:00.041(11)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Removing the option works fine.

FYI: I have installed imagemagick `sudo npm install imagemagick -g`

Any idea?

**Comment by tomitrescak** [comment]
The npm version of imagemagick is only wrapper for the binary version. You need to intstall the image magic on your server via macports or brew. Check first if it is working by trying to convert an image in the terminal. If it does so, I'm pretty sure it will work in upload control as well.

**Comment by tomitrescak** [comment]
I'll close this issue, reopen if necessary.

**Comment by rafaelfaria** [comment]
Sorry. Had forgot to reply. 

I had imagemagick installed through npm like i mentioned above, but i will look it up about installing with brew or port. Thanks for the help.

**Comment by rafaelfaria** [comment]
When you publish the project to meteor.com, does that supports imagemagick?

**Comment by tomitrescak** [comment]
I am almost positive that it does not. You need your dedicated server :/

**Comment by rafaelfaria** [comment]
I was afraid so! :) thanks

**Comment by j6k4m8** [comment]
Whew. This issue took me quite some time to track down! Is the ImageMagick dependency documented anywhere? Maybe there's a better way to fail than ENOENT...

**Comment by tomitrescak** [comment]
I have updated the documentation. Thanks.
