### ISSUE TITLE
autoStart

### ISSUE THREAD

**Issue by rafaelfaria** [tomitrescak/meteor-uploads#26]
How do i automatically start the upload as soon as i drag and drop the file?

I found one reference to it on the code "autoStart" but not sure how to make this work.

I tried something like:
{{> upload_semanticUI autoStart=true }}

Can't find in the documentation, could you please light some shed to me on this please?

thanks

**Comment by rafaelfaria** [comment]
I think the problem is in this line

```
// we can automatically start the upload
if (templateContext.autoStart) {
    Uploader.startUpload.call(templateContext);
}
```

I've changed to

```
if (templateContext.data.autoStart) {
```

and it worked! :)

**Comment by tomitrescak** [comment]
I am gonna close this issue, if needed, please reopen.
