### ISSUE TITLE
semanticUI Bug?

### ISSUE THREAD

**Issue by rafaelfaria** [tomitrescak/meteor-uploads#27]
I think i found a bug whilst trying to change the classes of the semanticUI

I have setup mine like below (not sure if i'm doing correct because i couldn't find anything on the documentation,please let me know)

```
	Uploader.UI.semanticUI = {
		upload: 'media-browse',
		progressOuter: 'media-browse-progress-outer',
		progressInner: 'media-browse-progress-inner',
		progressBar: 'media-browse-progress-bar',
		removeButton: 'media-browse-remove',
		removeButtonIcon: '',
		startButton: 'media-browse-btn-start',
		startButtonIcon: '',
		doneButton: 'media-browse-btn-done',
		doneButtonIcon: '',
		cancelButton: 'media-browse-btn-cancel',
		cancelButtonIcon: '',
		cancelledButton: 'media-browse-btn-canceled'
    }
```
Also, if i may suggest, this could be merged  into the defaults. So if i want to change just a name of one of the elements, i wouldn't have to replicate the whole object in order to do that.

So, back to the bug, If i replace the element startButton to whatever class i want, it doesnt work. The event might be still appended to the 'start' class because if i do the below it works.

```
startButton: 'start media-browse-btn-start',
```
I haven't digged into the code to be 100% sure but i think it's worth a look! :)

Hope it's fine to keep logging bugs that i find! :)

Thanks

**Comment by tomitrescak** [comment]
I really appreciate your efforts! I will check those classes .. but they do not look semantic ui :/ semantic is using class chaining to maintain the description of the element like "big red submitItem button". It's a different approach than bootstrap.

**Comment by tomitrescak** [comment]
I am going to close this issue. In case you feel like doing a pull request to check what you mean, I would appreciate that. Thanks!
