### ISSUE TITLE
client/init.js did not work

### ISSUE THREAD

**Issue by rafaelhdr** [tomitrescak/meteor-uploads#28]
Hello,

I tried
```javascript
// file: client/init.js
Meteor.startup(function() {
  Uploader.finished = function(fileInfo, templateContext) {
    Uploads.insert(fileInfo);
  }
})
``` 
(from README.md)
but did not work.

I solved by moving the file to root (and checking if isClient, and using templateContext)
```javascript
// file: init.js
if (Meteor.isClient) {
  Meteor.startup(function() {
    Uploader.finished = function(fileInfo, templateContext) {
      Uploads.insert(templateContext);
    }
  });
}
```

I tried this because of the [File Load Order](http://docs.meteor.com/#/full/fileloadorder).

Thanks

**Comment by tomitrescak** [comment]
Rafael, yes, this has to be executed only on the client, so your solution is correct. I do not understand yet, why would you insert template context to DB?

**Comment by tomitrescak** [comment]
I guess this all changed when I added the correct version of server to Meteor repository.

* Fixed in 1.1.1

**Comment by rafaelhdr** [comment]
Thanks. It is working fine :)

About the Template Context question, it is strange, but it is returning the fileInfo for me (i have no idea why).
I added:
```javascript
console.log(fileInfo);
console.log(templateContext);
```

And it is returning
```
0
Object {name: "myfile.txt", size: 16, type: "text/plain", path: "/myfile.txt", url: "http://localhost:3000/upload/myfile.txt"}
```

Is this happening only with me? Should i create another issue on GitHub, or we talk here?

**Comment by tomitrescak** [comment]
Rafael, please, check out the documentation. There were breaking changes in 1.1.1, when server is now returning fileInfo for better control. Making it work again is simple by using `fileInfo.name`.

**Comment by tomitrescak** [comment]
I will close this issue, please reopen if necessary.

**Comment by rafaelhdr** [comment]
Thanks.
Just confirming, it is working fine.

Probably i made an mistake with finished callbacks.
