### ISSUE TITLE
Clear uploader

### ISSUE THREAD

**Issue by townmulti** [tomitrescak/meteor-uploads#29]
No way to clear the uploader at will after an upload without refreshing the page.

**Comment by tomitrescak** [comment]
I am not sure what you mean. What do you mean by clearing the uploader ? Uploader is stateless and all information is passed in callbacks.

**Comment by townmulti** [comment]
I mean reset the form.

**Comment by tomitrescak** [comment]
Still not understanding. You mean the text on uploader? You can just set it with jQuery

**Comment by townmulti** [comment]
Okay, yes I mean the text, the progress percentage bar, and the Done button. Just want to set it to anew like it was before uploading anything.

**Comment by tomitrescak** [comment]
Well, when user clicks on the browse button again, he/she can upload another file, so there is no need to reload the page. Just in case if you really need that I have implemented a behaviour that when you click on the "Done" button it will reset the uploader to the initial state. I will release it in the next version.

**Comment by townmulti** [comment]
Okay ...makes sense. I will watch for the next version. Thanks for all your hard work!

**Comment by SwiTool** [comment]
I think I have to say a word here,
I noticed that it's not possible to add a file one we have chosen one already.
Example:
I click on Browse, then on Upload. Then on Browse
There should be a file list with the delete button, right ?

**Comment by tomitrescak** [comment]
Hmm, not really, file list with the delete button is not part of the interface. That you build yourself since I do not control how and where you store your files (collection, session ...).

**Comment by tomitrescak** [comment]
The list which I display is the upload queue if you are uploading multiple files.

**Comment by SwiTool** [comment]
Oh yes, I understand. Thank you for the fast answer.

**Comment by tomitrescak** [comment]
The new version  has the possibility to clear the uploader control by clicking on the DONE button.
