### ISSUE TITLE
Reload page after upload

### ISSUE THREAD

**Issue by eportico** [tomitrescak/meteor-uploads#31]
Why autoreload page after uploaded finish ? This is a problem why reinit data

**Comment by tomitrescak** [comment]
Not sure what you mean? Uploader does not reload page. Please provide me an example of what you mean, but in general uploader should not have this behaviour.

**Comment by tomitrescak** [comment]
Are you still having this problem? Please let me know if I can close this issue if it was a special deployment problem.

**Comment by aldidana** [comment]
it's just like hot code reload, when finished upload.

**Comment by tomitrescak** [comment]
Did you configure your upload directory as advised to the directory starting with a dot "." .. or to the directory outside of the meteor solution? Otherwise meteor will always reload your data.

**Comment by aldidana** [comment]
oh i see, this is because my upload directory was set to public/images.

**Comment by tomitrescak** [comment]
That is correct. That is why the tomb:meteor-server solution exists, so that you can serve file from any arbitrary directory and avoid the hot code reload.

**Comment by eportico** [comment]
Ok! thanks!!

**Comment by eportico** [comment]
but .... if upload outside server dir then can't server image uploaded ¿?

**Comment by tomitrescak** [comment]
No .. you just configure the tomi:upload-server to serve files from the defined directory under defined route. See the tutorial, it's all explained there.

I'm glad I could help, I will close this issue now. Please reopen if necessary.

**Comment by tomitrescak** [comment]
Just so you know what I am talking about, if you configure the upload server as following:

```javascript
//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/',
    checkCreateDirectories: true //create the directories for you
  })
});
```

You are now serving files from the hidden directory ".uploads" under the default route "upload". Route can also be configured.

Also, you can configure server to files from completely unrelated directory and server will serve them from there under the route "upload" :

```javascript
//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    tmpDir: '/path/to/any/directory',
    uploadDir: '/path/to/any/directory/tmp',
    checkCreateDirectories: true //create the directories for you
  })
});
```

**Comment by eboujlal** [comment]
add this at anyplace in your project
   ```
  Meteor._reload.onMigrate(function() {
            return [false];
        });
```
