### ISSUE TITLE
File uploaded but 'finished' not triggered

### ISSUE THREAD

**Issue by bensonnjonjo** [tomitrescak/meteor-uploads#32]
Weird problem, which is only present in remote server (works well in localhost), not sure what I'm doing wrong
- The file is uploaded to the folder
- Progress goes to 100% 
- Progress bar reverts back to 0
- Button flashes 'done' then goes back to 'cancel'
I'm then unable to upload a new file, any work arounds?

**Comment by tomitrescak** [comment]
Uff, that is really specific to your deployment. Had deployed this solution on several occasions with ump to my production servers with no issues (considering that all access priviledges are ok). Can you maybe get some logs from browser console or server? On console I am quite verbose on what is actually happening.

**Comment by bensonnjonjo** [comment]
Thanks tomitrescak 

Was hoping it was an issue you had encountered before, yes it is very specific to the server, I'll go though my setup again and try to trace the problem. Really appreciate the response. Closing the issue
