### ISSUE TITLE
formData is not inserted to collection

### ISSUE THREAD

**Issue by aldidana** [tomitrescak/meteor-uploads#33]
why {{>upload_bootstrap formData=specificFormData}} is not inserted into collection ?
i already create a helper for specificFormData.

**Comment by tomitrescak** [comment]
Uploader does not insert anything in the collection. This you have to do yourself at will. The format collection is passed in all callbacks. Does this answer your question?

**Comment by aldidana** [comment]
thanks tomi.

**Comment by tomitrescak** [comment]
Most welcome;)
