### ISSUE TITLE
Before Hook

### ISSUE THREAD

**Issue by suhaboncukcu** [tomitrescak/meteor-uploads#34]
Hi again, 

I'm playing with codes by merging your server with another front end pieces around there and enjoying so far. 

I'm at a point I need to hook the image file object to check it's exif info (with imagemagick currently) so I can save the file by rotating it first. 

I've tried to achieve this inside of finished function but unfortunately, imagemagick throws an error as "identify: no data returned" 

When I hard-coded the image path lastly uploaded, it works fine. 

So I have two questions. 

Does finished function run exactly after file saved to the disk? 
Is there any way I can achieve this before saving the image to the disk? 

Best,

**Comment by tomitrescak** [comment]
Answer to your first question is YES, the finished function is executed after the file was moved from the temporary location to the desired location with the desired file name.

The answer to your second question is, that unfortunatelly, currently it is not possible. But it would be a nice enhancement. I propose following:

On server side:
1. Implement a new hook  `validate(tempFilePath, newFilePath, formData) : bool` method that will execute right after file file was successfully uploaded to the server, but it is still in the temporary location. Method will return either true or false depending on the validation result. 
1. Implement a new hook `processImage(fileInfo, options, formData)` that will execute after the file was moved to the new location and in which you will be able to execute custom code to process the image. The default behaviour of the processImage method would be following (from existing code):
   ```javascript
function processImage(fileInfo, options, formData)
   if (options.imageTypes.test(fileInfo.name)) {
      Object.keys(options.imageVersions).forEach(function (version) {
        counter += 1;
        var opts = options.imageVersions[version];

        // check if version directory exists
        if (!fs.existsSync(fileInfo.folder + '/' + version)) {
          fs.mkdirSync(fileInfo.folder + '/' + version);
        }

        imageMagick.resize({
          width: opts.width,
          height: opts.height,
          srcPath: fileInfo.folder + '/' + fileInfo.name,
          dstPath: fileInfo.folder + '/' + version + '/' + fileInfo.name
        }, finish);
      });
    }
   ```

**Comment by Jusdev89** [comment]
Hey how are you again? this is exactly something i needed. but i am not completely sure what options mean? and thatnk you for this repo, i'm sure options is something simple.

**Comment by tomitrescak** [comment]
Validations now are implemented. User validation can be performed on client. To validate user on server, you have to create a secret and then you can validate user as well.

**Comment by lowi** [comment]
Hello Tomas,
I am using your package for uploading, and I like the idea of adding the hook processImage.
I think I can implement it by adding the function through UploadServer.init that would override the default implementation, correct?

**Comment by tomitrescak** [comment]
@lowi  That is correct. Thanks!
