### ISSUE TITLE
How do I pull the formData from the finished callback?

### ISSUE THREAD

**Issue by Jusdev89** [tomitrescak/meteor-uploads#35]
Hello,

Could you please help me out. I'm trying to basically upload a blog image and associate it with one individual blog post. I'm assigning the blog _id to formData on the template. Is there a way that I can get this data in the finished callback? That way I could update the blog record with the correct image url. Below is the source: 

```javascript
{{> upload_bootstrap formData=_id}}
```

```javascript
  UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/uploads',
    finished: function(fileInfo, formData) {
    	console.log(formData);
    	Campaigns.update({_id: formData}, {set: {image: fileInfo.path}});
    }
  })
```
Any suggestions would be great. Thanks for all your help.

**Comment by tomitrescak** [comment]
formData parameter is string Json. So ethe best way to go is described in the documentation:

```html
<template name="myTemplate">
{{> upload_bootstrap formData=myFormData}}
</template>
```

```javascript
Template.myTemplate.helpers({
  myFormData: function() { return { id: this._id }; }
})
```

**Comment by Jusdev89** [comment]
Thank you so much. You sir, are a gentleman and a scholar.

**Comment by tomitrescak** [comment]
Heh, thanks. Glad I could help. I'll close this issue, please reopen if necessary. I have also updated my response for future reference.
