### ISSUE TITLE
upload_bootstrap template browse button disabled

### ISSUE THREAD

**Issue by subatomicceo** [tomitrescak/meteor-uploads#38]
Cannot use {{> upload_bootstrap }} because the browse button renders with disabled as a class making it unclickable.

**Comment by tomitrescak** [comment]
Can you create minimally reproducible application or a meteorpad example? On my end all is good.

**Comment by subatomicceo** [comment]
Unable to recreate in a meteorpad however upon further inspection I noticed the issue appears to be cause by packages/tomi:upload-jquery/uploader.js lines 232 & 233. 

```
.prop('disabled', !$.support.fileInput);
.parent().addClass($.support.fileInput ? undefined : 'disabled');
```

It appears that $.support.fileInput is null when logging thereby causing my input buttons to always render as disabled.

**Comment by tomitrescak** [comment]
What browser are you using? 
jQuery is detecting that your browser is not supporting fileInput.
If you run $.support in browser console the "fileInput" has to be true.
This solution should work on all "modern" browsers.

**Comment by subatomicceo** [comment]
Using Google Chrome: Version 40.0.2214.111 (64-bit) on OSX Yosemite v10.10. Shot in the dark here but maybe because I have a new browser and '$.support' is deprecated? 

Found this: "For your own project's feature-detection needs, we strongly recommend the use of an external library such as Modernizr instead of dependency on properties in jQuery.support."

Src: http://api.jquery.com/jquery.support/

![screen shot 2015-02-12 at 10 16 06 pm](https://cloud.githubusercontent.com/assets/3360265/6183073/df264a4e-b304-11e4-813b-65598099b388.png)

**Comment by tomitrescak** [comment]
Wow. Looks like a jQuery issue then.
I have exactly the same configuration as you do and it works just fine.
Which version of jQuery you use? I guess it’s the standard one from meteor?



I’ll investigate, if you find out anything, please let me know.

Dr. Tomas Trescak
Postdoctoral Research Fellow in Digital Humanities  
School of Computing, Engineering and Mathematics
University of Western Sydney  | Locked Bag 1797 Penrith NSW 2751  
P:   02 9852 9082  |  M:   0487 261 213  
E:   t.trescak@uws.edu.au

On 13 February 2015 at 17:25:55, Greg Parks (notifications@github.com) wrote:

40.0.2214.111

**Comment by subatomicceo** [comment]
Aha! I was using jQuery v2.1.3, so I switched to v1.11.3 and viola! Thanks for all your help and for your awesome plugin!

**Comment by tomitrescak** [comment]
Good catch! Have to update it so that I support also the latest jquery. Thanks for you help! Glad you like the plugin. Still a long way to go to have all I like. Next destination are chunked uploads and resume;)

**Comment by genjurosama** [comment]
is this issue resolved yet , i'm experiencing the same problem .
how can i downgrade the version of my Meteor Jquery default package?

**Comment by tomitrescak** [comment]
Plugin works with default jquery. Only if you install a new version then
you may run into these problems. Tested on Mac and Linux. I didn't have
time to look into this issue further::

**Comment by genjurosama** [comment]
i use the default jquery that comes with Meteor

**Comment by tomitrescak** [comment]
That is not possible, the default version is v1.11.2 
At least as tested on Mac

**Comment by mitesh-mutha** [comment]
I am facing the same problem. Dropzone works but upload_bootstrap doesn't. I even installed the jquery plugin 1.11.3_2 additionally to check if it works and it doesn't. The issue remains the same. 

I have tried in Firefox as well as Chrome now. Let me know how i can solve this issue.

**Comment by spikey82** [comment]
I've seen the same issue when I updated, but it was not the disabled property causing the trouble but the 'style:left;' attribute causing the browse button to disappear. Try this in your template rendered callback:

$('.btn-file').removeAttr('style');

Not a permanent solution, but this works for me in the meantime.

**Comment by mitesh-mutha** [comment]
Yes @spikey82 , your solution does indeed work. Thanks. I will take this for now.

**Comment by Jusdev89** [comment]
Hey im having this same issue. my browser doesn't show the browse button. and @spikey82 answer keeps breaking my code. so how do i go back to a previous version.

**Comment by Jusdev89** [comment]
Nevermind my mistake. Thanks for the package bro its great!

**Comment by tomitrescak** [comment]
Guys, can anyone address this bug maybe? I'm really miserable on time right now. PR would be very welcome :100:

**Comment by tomitrescak** [comment]
Nevermind. 2.1.7 resolves this issue. Sorry about that.
