### ISSUE TITLE
unexpected server error

### ISSUE THREAD

**Issue by ningning-718** [tomitrescak/meteor-uploads#39]
Hi,

I followed your steps in the document to try the simplest example. But I run into trouble. Something wrong on the server side. The console output as below,

W20150213-16:23:17.156(8)? (STDERR) 
W20150213-16:23:17.160(8)? (STDERR) /home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/static.js:60
W20150213-16:23:17.160(8)? (STDERR)       next();
W20150213-16:23:17.160(8)? (STDERR)       ^
W20150213-16:23:17.162(8)? (STDERR) TypeError: undefined is not a function
W20150213-16:23:17.162(8)? (STDERR)     at resume (/home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/static.js:60:7)
W20150213-16:23:17.162(8)? (STDERR)     at SendStream.error (/home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/static.js:73:37)
W20150213-16:23:17.162(8)? (STDERR)     at SendStream.emit (events.js:95:17)
W20150213-16:23:17.163(8)? (STDERR)     at SendStream.error (/home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/send/lib/send.js:147:51)
W20150213-16:23:17.163(8)? (STDERR)     at SendStream.onStatError (/home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/send/lib/send.js:248:48)
W20150213-16:23:17.163(8)? (STDERR)     at /home/roger/.meteor/packages/tomi_upload-server/.1.1.1.b4xvxt++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/send/lib/send.js:320:26
W20150213-16:23:17.163(8)? (STDERR)     at Object.oncomplete (fs.js:107:15)

Can not find the next() definition.

Could you help me?

**Comment by tomitrescak** [comment]
Umph, did you manage to solve it? This error tells me nothing :/

**Comment by FridaG** [comment]
What kind of file were you trying to upload?  I get the same error, but only if I'm trying to upload certain mime types (docx, pptx, etc), and I've been scouring the internet trying to figure out how to fix it.

**Comment by tomitrescak** [comment]
Guys and Gals, I will need a minimally reproducible app to deal with this error. I'll close this issue now, please reopen if necessary or if you prepare the app for me ;)
