### ISSUE TITLE
502 Bad Gateway on Nginx deployment

### ISSUE THREAD

**Issue by conorstrejcek** [tomitrescak/meteor-uploads#40]
I have a few meteor apps deployed on subdomains of my Nginx server. Nginx routes these subdomains to the port which each app runs on. I am trying to use meteor-uploads in one of my applications, and I am getting a `502 Bad Gateway` error when I attempt an upload.

I'm not sure if this is a problem with how I have Nginx set up, or with deployed meteor projects using `meteor-uploads`.

![Here is a screenshot.](https://cloud.githubusercontent.com/assets/2925090/6195554/c9eca00c-b394-11e4-90b4-c21518901c67.png)

Let me know if you'd like more information (either about my Nginx configuration, or anything else).

I am wondering if I might have to set up some special routing for the `/upload` path.

Looking in the Nginx error logs, I can see `upstream prematurely closed connection while reading response header from upstream`, which might lead me to believe that the application is having problems, rather than Nginx.

**Comment by conorstrejcek** [comment]
I am tracking my app with Kadira and I found this was the error occurring:

`[server-crash] EACCES, open '/opt/<appNameHere>/.uploads/tmp/69bf59be4dafbdda6ab246c5514659aa'`

**Comment by tomitrescak** [comment]
The problem is, that you most probably do not have access to the given path :/
Looks like you are using Ubuntu server with mup.

Make sure that director: /opt/<appNameHere>/.uploads/tmp exists and that application has a right to write there.

**Comment by conorstrejcek** [comment]
@tomitrescak Thank you for the help, I got the upload to work by chowning the `.uploads` directory.

I just have one other question -- because I'm deploying with `meteor up`, my app's `ROOT_URL` is just `localhost`, so when the url is generated for the upload, it has `localhost:<my port number>` in the beginning. I want to replace this with the actual url of my deployment (I tested changing the url in the browser and it worked once I changed it), so I was wondering what you think the best way to do that is.

Should I just modify the `.url` attribute in the `Uploader.finished` function? The only reason I don't want to do that now is because hard-coding a url like that will become very annoying between testing locally and multiple possible deployments.

**Comment by conorstrejcek** [comment]
The url works just as well if I start at the `/uploads/` level, omitting the root url altogether, so for now I am doing:

`fileInfo.url = "upload/" + fileInfo.url.split("/upload/").pop();`

**Comment by tomitrescak** [comment]
Conor, fileInfo also contains the `path` property, which contains the relative path in the upload directory to your file. Therefore you can simply create the path to your file like this:

if you configured upload server to serve from '/uploads' directory then:
`var myUrl = '/uploads' + fileInfo.path;`

if you configured upload server to serve from '/myOtherUploads' directory then:
`var myUrl = '/myOtherUploads' + fileInfo.path;`

I am also using mup to configure the upload directory and sometimes I have problem with server not willing to serve files from the .upload directory. So I configure an environment variable in `mup.json` file like this:

```json
...
 "env": {
    "PORT": 3060,
    .
    "UPLOAD_DIR": "/opt/MyApp/Uploads"
  }
```

I make sure that app has a write access to that directory. And then, when running meteor on localhost, I run it as `UPLOAD_DIR=/path/to/dir meteor`

But, if your server is serving files from that hidden directory with no issues than you can forget this second part.

**Comment by newterminator** [comment]
@conorstrejcek I wanted to ask you that what command did you use to chown the /opt/<appNameHere>/.uploads/tmp or as @tomitrescak put it. 

I did chown -R root .uploads

**Comment by tomitrescak** [comment]
the best is to assure write to the app, while not the safest following will work for sure:

chmod o+rw .uploads
chmod o+rw .uploads/tmp

otherwise check who is the user that is executing the meteor app and chown to that user. By default the user is called `meteoruser`

`chown -R meteoruser .uploads`

**Comment by newterminator** [comment]
@tomitrescak Thanks Tomas for replying. I used all the 3 commands that you mentioned (including the command for chown as meteoruser) on the server but still the error remains the same.

I am attaching the error pic below:
![upload_error_server](https://cloud.githubusercontent.com/assets/5087437/6241235/ab9dc8d2-b6e7-11e4-8168-57e71dae75fe.jpg)

**Comment by tomitrescak** [comment]
try this:

`chmod a+rwx /opt/tedandkat/.uploads'
`chmod a+rwx /opt/tedandkat/.uploads/tmp`

**Comment by newterminator** [comment]
@tomitrescak Thanks for the two helpful commands which I used. The permission denied error is now gone, though I have got a new 'Unhandled error' thrown which I need to investigate further. So its a good news and a bad news. :)

**Comment by newterminator** [comment]
@tomitrescak I finally got the images uploading working. Turns out the new error thrown was due to not having imagemagick installed. 
Now the images are successfully uploaded to the server and the respective thumbnails are also generated but the I cannot view the images on the app. 
I put the following: 
"env": {
    "PORT": 3060,
    .
    "UPLOAD_DIR": "/opt/MyApp/Uploads"
  }

**Comment by tomitrescak** [comment]
you need to configure the tomi:upload-server to serve files from the very same directory and you are done:

//file:/server/init.js
Meteor.startup(function () {
  UploadServer.init({
    tmpDir: process.env.UPLOAD_DIR + '/tmp',
    uploadDir: process.env.UPLOAD_DIR,
  });
});

**Comment by newterminator** [comment]
@tomitrescak I put the code above as you mentioned in the server/init.js file and then gave the proper ownership to meteor user. The files are getting uploaded successfully but the images still cannot be displayed. Here is the image showing the files uploaded on the server.
![files_on_server](https://cloud.githubusercontent.com/assets/5087437/6262919/de4965b2-b7db-11e4-9613-e7cbd1c052df.jpg)

here is the app page online (its something I built for my wife) : http://tedandkat.com/pizza-hat 
Previously I was saving the pictures to folder hphotos but the last 2 pictures are in uploads folder as you can see in the image above

**Comment by tomitrescak** [comment]
Hey, I checked your app and I noticed that you are trying to serve files from the "/uploads" folder, while default is "/upload" folder. Have you been changing the configuration of your app?

**Comment by tomitrescak** [comment]
And surprise surprise ... your uploads on that url work.

http://tedandkat.com/upload/large%20(1).jpg

And you have a hot wife ... sorry for stalking!
I'll close this issue, please reopen if necessary.

**Comment by newterminator** [comment]
Thanks @tomitrescak so much for pointing that out...and thats not my wife's pic...it was just a demo pic :)

**Comment by huntonas** [comment]
I am not sure if this is related or not, but I am getting "Failed to load resource: net::ERR_CONNECTION_RESET" when uploading images after using mup to deploy to Digitalocean. I read through this feed and tried the things mentioned, but I am still getting the error. 
![2015-04-08_1228](https://cloud.githubusercontent.com/assets/3513403/7051032/e7a09b78-ddea-11e4-8bb9-b2bdf0d0f54d.png)

**Comment by greenwolfe** [comment]
This thread was very informative, and I now have meteor-uploads working on digital ocean with the upload directories set at /opt/MyApp/.uploads and /opt/MyApp/.uploads/tmp.  As an experiment, I tried using folders in the deploying users home directory (with owner and permissions set properly), but this did not work.  Is the uploads directory restricted to a subfolder of /opt/MyApp in this circumstance?  Are there any security concerns about storing the files here?  Would there be any other advantage to storing the uploaded files elsewhere, or should I be content with the solution as is?

Thanks,

Matt

**Comment by tomitrescak** [comment]
Matt, not sure why it did not work in the user directory ... it should have. But if it works from opt, then you're good. There are no security issues since upload server prohibits a directory change.

**Comment by greenwolfe** [comment]
If I decide to pursue saving the files in the user directory and can't get it to work, then I'll post some more details back here.  It is still helpful to know that it should work, and also that I can turn my immediate attention to other issues as its working now and is secure.
Thanks again,
Matt

**Comment by namirsab** [comment]
Hello Everybody!
I have the same problem. I've tried everything it's written  here. At first I had my .uploads directory in the /home/user/bundle/ directory ( the directory of the packaged app).
I tried all what you said but it didn't work. It uploads the images but when it callls the finished calllback it gives me a 502 error bad gateway.
I changed the dir to opt/appname/... as I've read here but it's still not working. It gives me the same error when it finished and it uploads the photo, but does not let me get the fileInfo in the callback.
When i look the nginx log it says this:
upstream prematurely closed connection while reading response header from upstream
So I don't know what's happening. I'm deploying in a DigitalOcean droplet with Ubuntu 14.04.

**Comment by wlundgren** [comment]
I experienced the 502 problem too. Read the previous entries to try this or that because the solution for you is very likely there. In my case, I needed to chown the directories to meteoruser (the owner was the user I use for ssh'ing the server). Btw, I am also using digital ocean with ubuntu.

**Comment by tomitrescak** [comment]
What does your server console say?
If it is a security issue you should have some info there.

**Comment by namirsab** [comment]
No server console. Its deployed with nginx and the log says what I said in
my first post. In the log of meteor is only written that the file was
uploaded.

**Comment by namirsab** [comment]
Another detail, i'm using https

**Comment by namirsab** [comment]
Sorry, I've found the problem. Imagemagick wasn't installed and the error was because the app couldn't create the thumnails. After I installed Imagemagick everything is ok. Anyway, I think it should be an issue apart from this, some warning message could be really nice for debugging and knowing what's happening.

**Comment by Xample** [comment]
I also had a similar issue but it is not related to Nginx. I deployed my meteor app from a docker container. Unfortunately, right after the upload I get this issue:
```bash
fs.js:555
web_1    |   return binding.rename(pathModule._makeLong(oldPath),
web_1    |                  ^
web_1    | Error: EXDEV, cross-device link not permitted '/built_app/.uploads/tmp/0427b1af9dea8d73af16b26465b14697
```
NodeJS seems not to handle the renaming of a file on different partitions. A solution is to use the proceedure described here: http://stackoverflow.com/questions/4568689/how-do-i-move-file-a-to-a-different-partition-or-device-in-node-js but it involves modifying fs.js… I have not found a workaround yet for this.

**Comment by ismetck** [comment]
hi,
Troubleshoot installation errors;
server commandline;
1. docker exec -it myapp apt-get install graphicsmagick -y //I do not use it anymore
client / myapp/mup.js script
2.   docker:{
      image: 'abernix/meteord:base',
      image: 'artyomjackson/meteord-imagemagick'
    },//Completely solved the problems
