### ISSUE TITLE
formData  not passed along

### ISSUE THREAD

**Issue by sorenriise** [tomitrescak/meteor-uploads#41]
Im not able to get the formData passed along -- the second callback parameter is always "undefined"

<template name='DZ'>
    {{> dropzone formData='xxx=name123'}}
    {{> upload_bootstrap formData='xxx=name123'}}
</template>

I20150214-16:29:19.001(-8)? GETDIR { name: '7.sql', size: 2617, type: 'text/x-sql' } undefined
I20150214-16:29:19.002(-8)? FILENAME { name: '7.sql', size: 2617, type: 'text/x-sql' } undefined
I20150214-16:29:19.002(-8)? FIN { name: 'zzz', size: 2617, type: 'text/x-sql', path: 'aaa/zzz' } undefined

My call backs (coffee script sniplets)...

        getDirectory: (fileInfo, formData) ->
            console.log "GETDIR", fileInfo, formData
            return "aaa";
         getFileName: (fileInfo, formData) ->
            console.log "FILENAME", fileInfo, formData
            return "zzz";
          finished: (fileInfo, formFields) -> console.log "FIN", fileInfo, formFields

**Comment by tomitrescak** [comment]
Form data is JSON. Try this:
{{> upload_bootstrap formData='{xxx=name123}'}}

**Comment by sorenriise** [comment]
Didn't work

**Comment by tomitrescak** [comment]
Well, then do as suggested in tutorials snd pass json data from helper.

**Comment by tomitrescak** [comment]
And I wrote my response on iPad so it still was not JSON"
{{> upload_bootstrap formData='{xxx:name123}'}}

And you may want to review the discussion ethics since I find your posts quite rude. This is an open source project which I do in my free time ...

**Comment by FridaG** [comment]
Yeah, his comment was rude, but I had a similar problem, and I was passing the formData from the helper.  Thank you for all the work, this is a really great package!

Template.myTemplate.helpers({
   formData: function(){
      var foo= Session.get('foo');
      return { 
        _id: this._id,
        directoryName: foo
         };
    }

**Comment by tomitrescak** [comment]
Dear FridaG, I have tested the passing the formData via helper and it seems that it works. I have created a small test application which you can download from [here](https://dl.dropboxusercontent.com/u/3418607/UploadTest.zip)

But, thanks to you guys I have found a bug in passing the form data via template and I have uploaded a patch online in 2.0.2. If you are passing data via template make sure it is a correct JSON:

e.g.:
{{> upload_bootstrap formData='{"xxx":"name123"}'}}

Both ways are showcased in the example app.

**Comment by tomitrescak** [comment]
I close the issue, please reopen if necessary.

**Comment by FridaG** [comment]
Awesome, thanks a lot!  I really appreciate the rapid responses.

**Comment by mazlix** [comment]
{{> dropzone formData='{"main": "true"}' }}

That is giving me undefined when i log formData. :(

**Comment by tomitrescak** [comment]
Hi, I have uploaded a patch. Just run `meteor update`. Version fixed: 2.0.3.

**Comment by FridaG** [comment]
Awesome, thank you, I got the formData to work perfectly :)

**Comment by mazlix** [comment]
:+1: Thanks! That fixed it!

**Comment by warrichrepos** [comment]
Hi, I'm having a problem getting formData to pass the correct data from a session variable. This is a wonderful package and this seems to be my only problem.

After my template loads, the initial value of formData 'myfolder' is set initially to nothing. When the session value changes via a select input option and I upload a file, it never uses the updated value from the session. I see from an example from above that this should work, but it does not. I'm sure I'm doing something wrong somewhere but I can't see where. If anyone could help or provide me with a clue that would be fantastic. Thanks again for the wonderful package.

[client]
Template.uploader.helpers({
   specificFormData: function() {
      
      var myfolder = Session.get('currentFolder');
     
      return {
        owner: Meteor.userId(),
        folder: myfolder        
      }
    },

[server]
if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
    
    UploadServer.init({
      tmpDir: process.env.PWD + '/.uploads/tmp',
      uploadDir: process.env.PWD + '/.uploads/',
      checkCreateDirectories: true, 

      imageVersions: {thumbnailBig: {width: 400, height: 300}, thumbnailSmall: {width: 200, height: 100}},

      getDirectory: function(fileInfo, formData) {
        
        console.log('fileInfo:', fileInfo);
        console.log('formData:', formData);
        return formData.owner + '/' + formData.myfolder;
      },
}
