### ISSUE TITLE
lacking Security controls: provide application control over the security and permission to upload

### ISSUE THREAD

**Issue by sorenriise** [tomitrescak/meteor-uploads#42]
Currently, the is no user information provided, and there is no server-side control over who is uploading files.

1. Meteor.user(), information needed within callbacks

Mteor.user() must be called from within a fiber, so it cannot be called directly from the callbacks.   Suggest that the user information is passed along so it is possible to check if the user are allowed to upload files, or better that the call is wrapped in a fiber so any meteor library can be used from within the callback. (for example, use helper functions rather than callbacks)

2. Provide a callback to reject the file upload.

There is no server side way of signaling that the file cannot be accepted -- e.g. as a result of user not having permissions.  Make the callback(or helper functions) able to return a "reject" with an error message.

**Comment by tomitrescak** [comment]
Sorenriise, thanks for your suggestions. Currently I'm out of capacity to do custom requests, the callback on validation is on my TODO list for a longer time already. PRs are most welcome, I could use some help. Thanks. If not, please have patience. Ciao.

**Comment by huntonas** [comment]
Could this be put into the validateRequest function? Check Meteor.userId() and then allow the upload or reject the upload based on that?

**Comment by tomitrescak** [comment]
No it can't. Upload server does not run in the Meteor thread, therefore it does not know about the user. You can send userid aspart of the formData. To be even more secure, you can generate secrets, check out iron router server routes for examples of how to do that.
