### ISSUE TITLE
Uploads do not work with Cordova

### ISSUE THREAD

**Issue by stormbkk87** [tomitrescak/meteor-uploads#43]
Does not work following the readme. Special settings for Cordova builds?

Failed 200 OK
data.sumbit.always:  textStatus= parsererror

iOS simulator

    UploadServer.init({
        tmpDir: process.env.PWD + '/public/uploads/tmp',
        uploadDir: process.env.PWD + '/public/uploads/',
        checkCreateDirectories: true
    });

**Comment by tomitrescak** [comment]
Unfortunately, I have not had a chance to test it for mobile. It is on my TODO list.

**Comment by tomitrescak** [comment]
Hmm, when I run it in the simulator in Safari on localhost:3000 everything works flawlessly.
Only when I run it as an App I get the 200 OK error.

**Comment by tomitrescak** [comment]
From what I see in the logs it is the problem of the simulator. Do you have a chance of running it on a physical device?

**Comment by stormbkk87** [comment]
Hi @tomitrescak. Same error on the device.

data.sumbit.always:  textStatus= parsererror

**Comment by tomitrescak** [comment]
Sh.t. there is some problem with Cordova then.
When submitting XHR request for file upload CORDOVA returns a full page and does not allow to upload. I will have to consult this with meteor team.

As mentioned earlier, the upload works in mobile browser.

**Comment by stormbkk87** [comment]
Yes, all works straightaway on the browser. Very good plugin. 

On Cordova, maybe your plugin is posting to http://meteor.local. This is the local server on the mobile phone. Maybe it needs to post to the server in ROOT_URL instead.

**Comment by tomitrescak** [comment]
HA! Thanks to your comments I have realised what the problem is and can announce full support of Cordova ;)

If you want to use it in Cordova app, you have to specify the full URL for the uploader:

```javascript
if (Meteor.isClient) {
  Meteor.startup(function() {
    Uploader.uploadUrl = "http://localhost:3000/upload";
  });
}
```

Thanks! I'll update the documentation.

**Comment by stormbkk87** [comment]
Great @tomitrescak! Glad to help.
