### ISSUE TITLE
Error deploying to meteors free servers

### ISSUE THREAD

**Issue by FridaG** [tomitrescak/meteor-uploads#44]
Hey, I feel bad opening up an issue because you were just so fast and responsive for a different one, but I was wondering if you happened to know if this package works with meteor's free demo servers?  I've tried deploying with `meteor deploy myapp.meteor.com`, but the site crashes, and when I look at the logs, it says `WARNING Error: EACCES, permission denied '/.uploads/'` and sites lines 355 and 61 from the upload_server.js package (`checkCreateDirectory` and `Object.UploadServer.init`)

Is this just an inherent limitation of those servers?  I've already tried making the directory non-hidden and got the same error, but I haven't deployed it to my digital ocean droplet yet.  

Thanks again for any insight!

**Comment by tomitrescak** [comment]
Hi, I'm pretty sure that the solution won't work on meteor servers exactly due to permission problems ;( Am thinking of including the file serving from DB but that is a future development.

**Comment by FridaG** [comment]
:) sounds good, thanks for letting me know.

**Comment by JackWReid** [comment]
The above is a shame, but totally understandable given permissions limitations. What server setups does this module definitely work with?

P.S. Devving locally at the moment and this module is seeming like godsend so far. Thanks!

**Comment by tomitrescak** [comment]
hi, was told that modulus servers work well, and I am deploying my application to dedicated Ubuntu servers using mup from Arunoda. I guess I should start on do serving;)

**Comment by FridaG** [comment]
Yeah, I use this package on digital ocean with nginx on a demo-run of my app right now for a small group.  So far it's working well, but I will swap to Galaxy hosting (assuming it's competitively priced) if meteor ever releases it.  They really got us all hooked on the ease of that `deploy` command, which was basically the inspiration for mup :)

**Comment by NguyenThaiHoc** [comment]
@tomitrescak   I am also deploying my application to dedicated ubuntu servers using mup,
when i chose file and upload, this was my screen, i dont know what is an error, but name of file didnt write on my databases, I guess my server dont allow to transfer file to it, I haven't solution,.. Do you have seen this error? help me!!!
![screenshot from 2015-04-19 15 49 39](https://cloud.githubusercontent.com/assets/7973490/7218823/ce0e4ea2-e6ab-11e4-821c-3e8bbd97ea7a.png)
