### ISSUE TITLE
Using meteor-server for a rest api implementation.

### ISSUE THREAD

**Issue by suhaboncukcu** [tomitrescak/meteor-uploads#46]
Hi,

I'm very glad to say that I'm using your meteor-server for yet another project of mine. I'm trying to build  a REST api with meteor and it has an image uploading feature. 

Currently, I can upload the file to the server without any problems but as a response (using hostname/upload path) I always get the same answer from the server including file name, path, etc. Is there any way I can change this respond? 

I've tried returning a dummy string on "finished" function but I can't see it from client. (This client btw, written in another language and not meteor client) Instead, as I said, I'm getting a json of files including name, path, size, url, etc. 

Best,

**Comment by tomitrescak** [comment]
Glad you like the project! You would have to modify behaviour of server. Look into Tomi:upload-server project. This is not customisable. If you find a good case example why such behaviour should be included in the core functionality, we can put a PR together.
