### ISSUE TITLE
Client side finished function incorrect params in docs

### ISSUE THREAD

**Issue by stormbkk87** [tomitrescak/meteor-uploads#47]
Hi @tomitrescak. Noticed the docs don't include the "index" param in the finished function (client side).

    // file: client/init.js
    Meteor.startup(function() {
      Uploader.finished = function(fileInfo, templateContext) {
        Uploads.insert(fileInfo);
      }
    })

should be

    // file: client/init.js
    Meteor.startup(function() {
      Uploader.finished = function(index, fileInfo, templateContext) {
        Uploads.insert(fileInfo);
      }
    })

**Comment by tomitrescak** [comment]
Good catch, corrected. Thanks.
