### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by benjick** [tomitrescak/meteor-uploads#49]
Hi

Trying to run this on Windows. ```process.env.PWD``` isnt' available so I tried the full path and ```process.cwd()``` to no avail. I just get a double C:\ in the path.

    Error: ENOENT, no such file or directory 'C:\C:\dev\infoAdmin\.meteor\local\build\programs\server'

Any clue what I might need to do?

**Comment by tomitrescak** [comment]
Hi, I am not familiar with meteor on windows. I advise you to explore what is contained in "process.env.PWD" and then use that to create a path in the Upload server configuration. Please report your finding so others can learn. Thanks!

**Comment by tomitrescak** [comment]
I will close this issue for now. Please reopen if necessary,

**Comment by mesosteros** [comment]
process.env.PWD is undefined on Windows.
process.cwd() will get you something like this: C:\Users\yourUserName\Desktop\Projects\fileUploadsMeteor\.meteor\local\build\programs\server
You need to exit to the app root folder and then go into .upload (I'm also attempting this). I'll edit this when I figure it out.

**Comment by Akamaozu** [comment]
@mesosteros Thanks so much for the help! 

Been looking everywhere and found no solution to this problem. I needed to add two more ..\ to my path to compensate, but it's working correctly now :+1:

**Comment by mesosteros** [comment]
Glad to be of help @Akamaozu :smiley:

**Comment by tomitrescak** [comment]
What needs to be done to make it Windows ready? Thanks for any advice.
