### ISSUE TITLE
if file size is greater than maxFileSize, no error is thrown or logged. 

### ISSUE THREAD

**Issue by calebl** [tomitrescak/meteor-uploads#50]
It just looks like the upload failed from the user perspective, with no way of notifying them as to why

**Comment by tomitrescak** [comment]
The new version will return 403 error when file is too big and won't be uploaded. While doing that I threw in client and server validations so that you can check for it directly on client. Please close if this solves your issue.

**Comment by calebl** [comment]
Sounds great. When will it be available?

**Comment by calebl** [comment]
Looks great! Thanks! Awesome package

**Comment by llaine** [comment]
Hi, how can I catch the error on server / client ?

**Comment by tomitrescak** [comment]
You have a `validate` method available on client who exposes access to the file.
