### ISSUE TITLE
Refreshing template

### ISSUE THREAD

**Issue by adriamooney** [tomitrescak/meteor-uploads#52]
Is it possible to refresh the template back to its original state after its finished successfully. I have an event that shows and hides the uploader template.  I'd like to refresh the template back to its original state if it is in its 'successful uploaded state', using this event.

**Comment by tomitrescak** [comment]
Hi, sorry for the late reply. When you click on the "Done" button the template is reset to the original state. The easiest way of approaching automatic reset is to hook on the `finished` event like this (not tested):

```javascript
// file: client/init.js
Meteor.startup(function() {
  Uploader.finished = function(index, fileInfo, templateContext) {
    $('.done').click();
  }
})
```

I will close this issue, please reopen if necessary.
