### ISSUE TITLE
How can you make different user's file uploads go to different sub-directories on server?

### ISSUE THREAD

**Issue by foxaal** [tomitrescak/meteor-uploads#53]
First of all, this seems like a great file upload package.  Very easy to get going.  Many thanks.  And your image reminds me of the movie Zardoz with the floating head -- somehow hypnotic.  I see reference on the meteor-tomi-upload-jquery package to DEMO which shows all the different options, but I cannot find that demo in the distribution.   So I am wondering the best way to automagically store a given user's file uploads to a subdirectory with that user's id or username or something.  Is there a mechanism in place for that?

**Comment by tomitrescak** [comment]
@foxaal head is from The Red Dwarf series, it's Holly, has IQ 6000, [QUOTE] "same as 6000 P.E. teachers" ;)

The DEMO application is where you currently are posting, the meteor-uploads app which showcases all the possibilities of the upload.

The easiest way of saving data to user's name subdirectory is to pass user ID as part of the `formData` and then on server use the `getDirectory` callback to return the name of the subdirectory where you want to save the file. See the documentation in here to check out both on `formData` and `getDirectory`.

**Comment by foxaal** [comment]
Well that's just jim-dandy!  A *formidable* proposition indeed.   Thank you, Holly.

**Comment by foxaal** [comment]
Here is the type of thing then -- seems to work well...liking this package...

HTML:
`{{ > upload_bootstrap fileTypes='.jpg' multiple=true formData=userData }}`

JS CLIENT:
`Template . uploadTemplate . helpers ( {
     userData : function ( ) {
        if ( Meteor . user ( ) && Meteor . user ( ) . username ) 
            return { userId : Meteor . user ( ) . username } ;
        else 
            return { userId : "blank" } ;
  }`
JS Server:
`  UploadServer . init ( {
      tmpDir : process . env . PWD + "/.uploads/tmp" ,
      uploadDir : process . env . PWD + "/.uploads/" ,
      getDirectory : function ( fileInfo , formData ) {
        return formData . userId ;
      } ,
      checkCreateDirectories : true //create the directories for you
  } )`
