### ISSUE TITLE
Issue with exampe

### ISSUE THREAD

**Issue by jhmacdon** [tomitrescak/meteor-uploads#54]
I cloned this repo and the first time I upload an image, this happens (but only the first time after Meteor starts):

<code>
W20150305-14:05:17.421(-5)? (STDERR)       next();</code>
<code>
W20150305-14:05:17.421(-5)? (STDERR)       ^</code>
<code>
W20150305-14:05:17.422(-5)? (STDERR) TypeError: undefined is not a function</code>

**Comment by tomitrescak** [comment]
Could not reproduce. :/ did you solve it?

**Comment by jhmacdon** [comment]
Not officially but I can no longer reproduce it either.
