### ISSUE TITLE
trouble with cyrillic images

### ISSUE THREAD

**Issue by Menogus** [tomitrescak/meteor-uploads#55]
they upload to server normaly, but dont want to load on view like: 
http://192.168.2.114:3000/upload/Братльнаякартинка.jpg
error: 404 - not found

with english names - all ok

**Comment by tomitrescak** [comment]
This is out of my reach, not sure how o handle this. I can't test it, you provided path to local host. Create a reproducible test app. Thanks.

**Comment by tomitrescak** [comment]
I am closing this issue, please reopen if necessary.

**Comment by toksea** [comment]
Same issue for Chinese filenames
