### ISSUE TITLE
upload and dropzone cross communication and some finer communication

### ISSUE THREAD

**Issue by wmodes** [tomitrescak/meteor-uploads#56]
First, thanks for an excellent package.

When I have a uploader and a dropzone on the same page, I notice there is a little bit of communication between them already. For instance, I think when I upload a bunch of files in the uploader, the dropzone displays the percentage complete.

However, when I drop files into the dropzone, I wish that the files appeared in the list of the uploader as they were uploading and afterward to show their status. As it stands, the dropzone is a bit of blackhole. Did it succeed? Who knows? Is it possible for them to share list, statuses, and percentages?

        <div id="upload-row" class="upload-row">
            <h3>Images Video and Audio</h3>
            Upload all images, video and audio files here.
            {{> upload_bootstrap fileTypes='.jpg,.png,.mp4,.wav,.mp3' 
                multiple=true formData=specificFormData }}

            <p>Or drag and drop files on the target area</p>
            {{> dropzone contentType='images' fileTypes='.jpg,.png,.mp4,.wav,.mp3' 
                multiple=true formData=specificFormData }}
            <p>Once you upload your files, you don't need to do it again unless the files are changed 
            or updated.</p>
        </div>

`formData=specificFormData` is just left there from copying from the examples.

Also, I wish I could change the text that appears in the dropzone easily.

And lastly, at one point during development when I was uploading files, the percentage displayed in the dropzone said "NaN%". I haven't tried to replicate that since, but was curious if there was something I could do to prevent it.

**Comment by tomitrescak** [comment]
Wmodes, can you please prepare a small test app for me with your scenario. This looks like a pile of bugs I need to address ;/

**Comment by huntonas** [comment]
I am getting the "NaN%" now when trying to upload images to my site. Not sure why it started, but it happened when I switched from modulus to digitalocean. I used meteor up for deployment to DO.

**Comment by huntonas** [comment]
found issue #40 and will try that out. Sorry if mine was a repost

**Comment by tomitrescak** [comment]
This shall be fixed in latest.
