### ISSUE TITLE
Communicating finished status back to form

### ISSUE THREAD

**Issue by wmodes** [tomitrescak/meteor-uploads#57]
Is there any way to communicate the status of the finished callback to the calling form? This would be useful to report if say the finished callback failed.

**Comment by tomitrescak** [comment]
Version 2.1.2 now exposes following callback:

```javascript
Uploader.status = function(error, data, textStatus, jqXHR) {
  console.log(error + " " + data + " " + textStatus + " " + jqXHR)
}
```
enjoy ;)

**Comment by pierreozoux** [comment]
Hi,

I don't get how I could use it.

Let's take an example like https://github.com/tomitrescak/meteor-uploads/blob/master/server/init.js#L25

If I write the following:
```
Items.update({_id: formData._id}, { $push: { uploads: fileInfo }}, function(error, documents){
  Uploader.status(error);
});
```

Will it work? Because I tried, without much success...

Thanks!

**Comment by tomitrescak** [comment]
Not sure what you want to do. The client is notified automatically. This is used more by database updates.
