### ISSUE TITLE
Uploading auto start when file added

### ISSUE THREAD

**Issue by meule** [tomitrescak/meteor-uploads#59]
How to achive it (without start button click)?

**Comment by jhmacdon** [comment]
<code>Meteor.startup(function(){</code>

<code>  $(document).on("change", "input:file", function(){</code>

<code>    $('.upload-control.start').click()</code>

  <code>    });</code>

<code>  });</code>

**Comment by tomitrescak** [comment]
Version 2.1.2 brings back the functionality of autostart, just do:

```html
{{> upload_bootstrap autoStart=true }}
```
