### ISSUE TITLE
Using package jonblum:jquery-cropper

### ISSUE THREAD

**Issue by guidouil** [tomitrescak/meteor-uploads#64]
Hi, your package is so simple regarding file upload that I love it :+1: 
how will you recommend to work with this package jonblum:jquery-cropper ?
https://github.com/jonblum/meteor-cropper
My will is to have a modal window where you are force to crop the image and then the upload it.
Is it possible to do so ? where should I start ?

**Comment by tomitrescak** [comment]
@guidouil thanks!

Yet, I don't really have the capacity to study custom development tasks :/ This site is used to track bugs/enhancements/problems with the software. I advise you to consult software development websites such as StackOverflow.

From what you say, all you need is tomi:jquery-upload-server to which you can post the files cropped by the package you mention.
