### ISSUE TITLE
must set multiple=true (or false) for dropzone to work, dropzone upload queue not cleared

### ISSUE THREAD

**Issue by greenwolfe** [tomitrescak/meteor-uploads#65]
To create this error:  
  meteor create --release 1.0.3.2 uploadsTest
  meteor add tomi:uploads-server
  meteor add tomi:uploads-jquery
  meteor add twbs:bootstrap

server/init.js and client/styleSheets/uploadsTest.css copied exactly from your quick start code.
client/uploadsTest.html:
```
<head>
  <title>uploadsTest</title>
</head>

<body>
  <div class='container-fluid'>
    <div class='row'>
      <p>Basic upload-bootstrap</p>
      {{> upload_bootstrap multiple=true}}
    </div>
    <p>Drop Zone</p>
    {{> dropzone multiple=false}} 
  </div>
</body>
```
result:  without multiple=false in the dropzone template insert, dropping a file adds it to the upload queue (render.drop and render.add in the console) but does not complete the process by uploading the file.  With multiple=false, the upload is completed.

result:  After uploading one file using the dropzone, drag a second file to upload.  The first file is uploaded again and a duplicate copy is placed in /.uploads along with the second file.  This continues.  If a third file is dragged, duplicate copies of the first and second files also appear.  It seems that the upload queue is not being cleared.

I had no problems using upload-bootstrap.  This is a nicely formatted file upload solution, and very easy to set up and use.  Really like it. Just passing along my observations.

**Comment by tomitrescak** [comment]
Yes, the dropzone got left behind, was not sure if people are using it. I'll test it properly this week and remove the bugs you mentioned. Thanks for reporting it!

**Comment by greenwolfe** [comment]
Thanks for creating and maintaining this and looking into this bug. 

I also found a similar error in the normal upload-bootstrap with multiple=true.  Progress bars are created for each file and not cleared.  If you click on done and then upload again, all the files in the queue are uploaded a second time.  Seems like the queue should be cleared automatically after successful upload, and you should have some way to clear the progress bars, perhaps clicking on their individual done buttons to clear them one at a time or clicking on the overall done button to clear them all at once (as that button returns to upload).

I plan to use the dropzone as a supplement to the standard upload, as wmodes described in issue 56, so the cross communication between the two would also be nice.  For example, have an upload-boostrap with a linked dropzone below it.  Browsing for files or dragging them into the dropzone fills the upload queue, then you click the upload button to upload the files.  

There is no problem using upload-bootstrap with multiple=false as that provides all the functions.  The drag and drop and multiple upload are nice extras, though.

**Comment by BeggarsMattM** [comment]
Aha, I've just discovered this - a very similar issue to what I've been experiencing.

I can't get upload-bootstrap to work myself though :(

**Comment by tomitrescak** [comment]
Hi, the newest version solved this issue (2.1.4). Sorry for the late answer. I will close this issue, please reopen if necessary.

**Comment by greenwolfe** [comment]
The queue now seems to be cleared as it should.  However, dropzone still only works if multiple is explicitly set.  Whether setting multiple=false or multiple=true, it operates as if multiple=true.  multiple=true now seems to be broken for upload_bootstrap, which only operates in multiple=false mode, but its queue is now also cleared after each upload as it should be.

Not sure how to reopen an issue.  Does just posting this comment do it?

Thought your response was pretty prompt.  Once again, thanks for working on this.

Matt

**Comment by tomitrescak** [comment]
Yes, I seem to mess up the multiple uploads. I'll fix it now. But the drop zone works just fine for me in the demo app. When you try the demo app, it still does not work ?

**Comment by tomitrescak** [comment]
OK, how about now.
From the tests:

* Dropzone works without setting the multiple, which is now automatically set to accept multiple files
* Queue is cleared correctly and bootstrap works as it should

**Comment by greenwolfe** [comment]
Yes.  All working properly.
Thanks!

Matt

**Comment by tomitrescak** [comment]
Thanks for the confirmation. Please reopen this issue if necessary.
