### ISSUE TITLE
Thumbnails in Semantic UI / Dropzone

### ISSUE THREAD

**Issue by mesosteros** [tomitrescak/meteor-uploads#67]
Is it possible to add Thumbnails of the uploaded files in the Semantic UI or Dropzone templates? I don't want to use Bootstrap but I could use this feature in one of these two.

**Comment by tomitrescak** [comment]
thumbnail display is up for everyone to code, since this is what differed in most applications and users want to display it at different parts of the page. For example of how to code that, please see the meteor upload application.

**Comment by mesosteros** [comment]
I described my issue incorrectly: what I want to know is how to display a preview image of the file to be uploaded before I actually click the upload button.
I already can display the thumbnails of already uploaded images.
I just need it before the actual upload.

**Comment by tomitrescak** [comment]
You can hook onto the `validate` callback on client and grab image there and display it wherever you need.
