### ISSUE TITLE
Im using this feature {{> upload_bootstrap }}. How do i set it so it doesn't reload my page?

### ISSUE THREAD

**Issue by Jusdev89** [tomitrescak/meteor-uploads#68]
Thank you. And Can i use this in production?

**Comment by tomitrescak** [comment]
Of course, it's open source, MIT License

**Comment by tomitrescak** [comment]
It won't reload your page when you will upload to the hidded directory, e.g. '.uploads' which is not picked up by hot code reload. I will close this issue now, please reopen if necessary.
