### ISSUE TITLE
When does "finished" callback get called?

### ISSUE THREAD

**Issue by BeggarsMattM** [tomitrescak/meteor-uploads#69]
Hi there,

I'm enjoying using this plugin but don't fully understand it yet and perhaps you can help me with an issue I'm having.  Essentially I'm using a fairly default dropzone:

{{> dropzone contentType='images' fileTypes='.jpg' multiple=false formData=specificFormData callbacks=myCallbacks }}

and a "finished" callback that inserts some of the fileInfo/formFields data into an Uploads mongo table. 

Unfortunately what I'm seeing is the Uploads table getting populated in "triangular" sequence - on my first upload one entry is added, on my second the new entry is added, plus the previous entry is added - and then thereafter, every time finished is called it not only adds a new entry, but re-adds all the previous entries in the Uploads table! 

I assume I'm doing something really silly, but can you cut through the confusion and give me any clue why the "finished" callback would be called one time for each upload that has been done to date?

Many thanks.

**Comment by BeggarsMattM** [comment]
Incidentally I can't get either {{> upload_bootstrap }} or {{> upload_semanticUI }} to work for me at all (503 errors every time), which may be completely a side issue or may be an insight into the fact that I've done something terribly wrong which is breaking my whole experience...

**Comment by BeggarsMattM** [comment]
Hmm, if I wipe the database then I upload one new file, all files I have uploaded this session get reuploaded. Should I be resetting the contents of the dropzone in some way that I'm not doing I wonder...?

**Comment by tomitrescak** [comment]
@BeggarsMattM I have updated the plugin so that queue is now wiped before any file is added to the upload control. Please let me know if this solved your issue. Version 2.1.4 is the newest one.

Sorry for the late response, but I was moving between Australia and Europ back and forth ... crazy time. If ll good, please close this issue.
