### ISSUE TITLE
Drop zone Error

### ISSUE THREAD

**Issue by iSuslov** [tomitrescak/meteor-uploads#75]
I got "Uncaught TypeError: Cannot read property 'callbacks' of null"
after dropped file in dropzone

**Comment by iSuslov** [comment]
Seems like if template has no data context then this error occurs

**Comment by iSuslov** [comment]
Appears when your template has no data context.
Workaround is 
 {{#with dropzoneData}}
 {{> dropzone }}
 {{/with}}

**Comment by kenrogers** [comment]
I'm getting the same dropzone error but this just makes my dropzone disappear. Is there a data context that I need to be adding to my template to get this to work?

**Comment by iSuslov** [comment]
You can do that:
Template.home.helpers({
  myCallbacks: function() {
    return {
        finished: function(index, fileInfo, context) { ... },
        ...
    }
  }
});


<template name="home">
    {{> upload_bootstrap callbacks=myCallbacks }}
</template>

**Comment by HunjaeJung** [comment]
It's very helpful! thanks!

**Comment by tomitrescak** [comment]
This has been fixed now. Buggy bug ...
