### ISSUE TITLE
file upload response data

### ISSUE THREAD

**Issue by sunstorymvp** [tomitrescak/meteor-uploads#76]
Hi!
Is there an ability to change default response data from UploadServer?

from this:
```javascript
{
  "files": [{
    "name": ...,
    "size": ...,
    "type": ...,
    "error": ...,
    "path": ...,
    "url": ...
  }]
}
```

to something like this:
```javascript
[
  { "link": ... },
  { "link": ... },
  { "link": ... }
]
```

or just:
```javascript
{ "link": ... }
```

Thanks!

**Comment by tomitrescak** [comment]
Dmitriy, not really unless you fork and modify the project. But why is that the problem? It's easy to get the url (link) from that response.

**Comment by sunstorymvp** [comment]
I will explain. I'm using https://github.com/froala/meteor-froala WYSIWYG and there is an option to upload images https://www.froala.com/wysiwyg-editor/docs/options#imageUploadURL, but editor waits for the response like {link: 'path/to/image.jpg'} and there is no options to parse another response data. That is the problem. I can't change the response data, or rules how to parse it.

**Comment by sunstorymvp** [comment]
Ok. I modified package to solve this problem. I hope i'm not missed something. https://atmospherejs.com/sunstory/upload-server

**Comment by tomitrescak** [comment]
Great! Glad you could solve it ;)
