### ISSUE TITLE
upload to a different server

### ISSUE THREAD

**Issue by nick-preda** [tomitrescak/meteor-uploads#79]
hi guys,
I saw on the blueimp documentation that it is possible to upload the files on a different server.

I am creating a multi-node meteor application, and would like to gather all the uploaded files to another server. 
is it possible with this package?

cheers,
nick

**Comment by tomitrescak** [comment]
Just point the uploader component to the server url where you want to perform upload: 

```javascript
//file:/client/init.js
Meteor.startup(function() {
  Uploader.uploadUrl = 'http://my.other.upload.url'
});
```

**Comment by tomitrescak** [comment]
Please close this if this solved your isssue.

**Comment by MeKarina** [comment]
hi @tomitrescak I interested with this. Could you please make a little bit further explanation or reference how to upload to different server? For example, how to setup the target server. Or is that really that magic just to put that code

```
//file:/client/init.js
Meteor.startup(function() {
  Uploader.uploadUrl = 'http://my.other.upload.url'
});
```

thank you so much

**Comment by Shelagh-Lewins** [comment]
I'd also like to know this: surely there is something you need to do on the target server to make it accept the file?
