### ISSUE TITLE
Request for help:  autofilling upload queue

### ISSUE THREAD

**Issue by greenwolfe** [tomitrescak/meteor-uploads#81]
If the meteor app has stored a file path on the local computer (e.g. c:\clients\folder\on\local\computer\filename.ext) can I add this path to the upload queue?  

I know that the local filesystem is sandboxed away from the browser (except maybe for chrome currently), so the answer to this question may well be that what I want to do is not possible.  

However, something similar must happen when the user browses to a file on their local machine. When they click on the file, it is added to their upload queue.  Then it is uploaded when they click on the upload button.  So in other words what i want to know is whether the browse step can be skipped if the path and filename are already known.

Thanks,

Matt

**Comment by tomitrescak** [comment]
With JavaScript, it is not possible, thank god;) it would be a massive security threat. Can we close this?

**Comment by greenwolfe** [comment]
Thanks for confirming.  That's what I thought.  It's closed.
