### ISSUE TITLE
Use it with Collection2

### ISSUE THREAD

**Issue by myhusam** [tomitrescak/meteor-uploads#82]
This package works fine with me! but when I use it with `Collection2`  to update the Profile in Meteor.users collection I got this error:

`POST http://localhost:3000/upload 503 (Service Unavailable)`

While when I try it without `Collection2` it works!

Is it a normal issues?

**Comment by tomitrescak** [comment]
Not really.I am successfully using the collection2 package along with the upload component in several of my projects.

**Comment by myhusam** [comment]
@tomitrescak that's cool. I'll try to figure it out why it's not working

**Comment by zirexba** [comment]
I have this problem with meteor 1.3.1 on Win 10.
Even original project from https://github.com/tomitrescak/meteor-uploads has the same problem at my PC. 
Tried some solution but nothing works...

**Comment by tomitrescak** [comment]
Hi, I will need a report for this as I do not have this problem nor can I simulate.
Collection2 does not interfere with the plugin at all so the error has to be in one of your callbacks, make sure you are inserting correct data according to your schema.
