### ISSUE TITLE
Getting cross domain request error?

### ISSUE THREAD

**Issue by SturmDrangAltaar** [tomitrescak/meteor-uploads#84]
Hi,

Firstly, great module, thanks!

It's been working fine on my localmachine, but as soon as I deployed it to the server, I get cross domain request error, see below:
```
XMLHttpRequest cannot load http://[IP]/upload. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://[IP]:8000' is therefore not allowed access.
```

I see that it's not adding the port number onto the requested url, could that be it?

This is just a staging site, hence I'm running on the IP:port. I imagine putting it on a domain would fix this, but I'd still like to try out first. 

Any help would be awesome!

UPDATE:
I removed the absolute URL declaration on the server, now I get the following:
net::ERR_CONNECTION_REFUSED

**Comment by tomitrescak** [comment]
Sturm, so far I had no such issue since I always call uploads from the same site. If you are using package for domain control I advise you to remove it and test if it work, or on contrary set up cross domain requests by allowing all requests.

**Comment by SturmDrangAltaar** [comment]
Thanks.
I've set up the site with a domain, reverse proxy through nginx.
Unfortunately the problem still persists.
I've added BrowserPolicy.content.allowOriginForAll for the domain as well as the IP, but still no luck.

I guess my last resort is to remove the browser-policy module, what's the security implications of this though?

**Comment by tomitrescak** [comment]
@SturmDrangAltaar , I'm no expert in this:/ I am not using the browser policy in my projects as I had also problems setting it up with other problems, not uploads. Please report back if you find anything new.
