### ISSUE TITLE
Making sure scaled images are JPG

### ISSUE THREAD

**Issue by hamoid** [tomitrescak/meteor-uploads#85]
What would be the easiest way to make sure images are stored in JPG format, independently of the upload format? Currently the format is maintained. So if someone uploads TIF, the thumbnail is TIF, which can not be displayed by the browser and it's heavy too. 

Side note: it would be nice to have access to all the ImageMagick power, not just scaling down images in a predefined way. People might want to crop instead, or use some of the great features ImageMagick provides.

**Comment by hamoid** [comment]
Maybe a nice way to achieve this would be with:

    imageVersions: {
      large: {width: 1500, height: 1000, format: 'jpg'}, 
      medium: {width: 600, height: 300, format: 'jpg'},
      small: {width: 300, height: 300, format: 'jpg'}
    },

**Comment by tomitrescak** [comment]
There is a `validate` and a `finished` callback to handle server activities so you have a complete power to perform imagemagick activities on server and return this new information. The functionality that you mention would be useful for some users but in general it will only unnecessarily increase the size of the package for the rest. A fantastic way of solving this would be creating a "plugin" or extra package that would automatically set up your mentioned functionality.

**Comment by tomitrescak** [comment]
I will close this for now as I do not plan on implementing this, but if you want to tackle it, it would be fantastic.

**Comment by hamoid** [comment]
I did implement it :) It's just 7 lines of code: 
https://github.com/tomitrescak/meteor-tomi-upload-server/pull/6
