### ISSUE TITLE
Upload Works, But Display Issue

### ISSUE THREAD

**Issue by bradthebluefish** [tomitrescak/meteor-uploads#86]
Hey there. I have successful used tomitrescak's to upload pictures to my MeteorJS app. All the images can be seen in the respective upload folder. 

However, none of the pictures will display in the {{ uploadedInfo uploads }} handlebar section or any other section as suggested. Any thoughts or suggestions?

**Comment by tomitrescak** [comment]
Brad, that would be fault somewhere in your implementation. The callbacks provide you either with file itself (validate) or with url to the uploaded file (finished). How you handle these callbacks is completely in your management. I don't think I can help here. Did you manage to solve this problem? If so, can you please close this issue?
