### ISSUE TITLE
What is the name of the function that starts the file upload?

### ISSUE THREAD

**Issue by FridaG** [tomitrescak/meteor-uploads#88]
I have an upload modal, but I'm finding that users are not successfully uploading because after they choose the file to upload, they just hit "Finished" and exit out of the modal without ever clicking the "upload" button.  Obviously I could just validate the modal and require them to upload before they hit exit, but it seems like it would be a more fluid user experience if I could just trigger the upload when they exit the modal.  I wanted to just call the "upload" function when the user clicks the confirmation button, but I don't know the name of the function to call!  

edit: is it just  Uploader.startUpload ?

**Comment by tomitrescak** [comment]
Sorry for the very late answer, I guess you figured it out by now.  But just for completeness it is it can be found [here](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L54) `Uploade.startUpload`.

**Comment by FridaG** [comment]
no worries, thanks for the response, I always appreciate your work on this project
