### ISSUE TITLE
Can't access Meteor.user() in server finished callback

### ISSUE THREAD

**Issue by scottyallen** [tomitrescak/meteor-uploads#89]
I'd like to tag upload files with the user id in the finished callback.  However, when trying to access Meteor.user() in the finished callback, I get:

Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
    at Object.Meteor.user (packages/accounts-base/accounts_server.js:24:1)
    at Object.fileUploadFinished [as finished] (app/server/init.js:5:31)
    at packages/tomi:upload-server/upload_server.js:413:1

I've seen the workaround of passing up the client id in the form data in another issue, but this isn't secure, as a user could easily pass another user's id.

**Comment by tomitrescak** [comment]
Duplicate, Please see #58
