### ISSUE TITLE
Recommendation for docs

### ISSUE THREAD

**Issue by elfatherbrown** [tomitrescak/meteor-uploads#91]
Hi Tomi,

Thank you for a truly masterfull package. 

Just a recommendation: the callbacks on the server side, validations, do not run in a fibre (I get a bunch of errors if I try to access any collections: wont run in a fibre, etc.). However, in the finished callback, is where we can operate with our collections.

For newbies like me, it would save a lot of time if you just put somewhere in the docs: "you can only access collections directly in the finished callback". 

Thank you again!

**Comment by tomitrescak** [comment]
Thanks for the recommendation. I have updated the documentation. It is not possible to run these callbacks in Fibre since I need synchronous answers to initiate data transfer. Therefore it is not possible :/ Please close if you are satisfied with the change.

**Comment by elfatherbrown** [comment]
Thank you sir!
