### ISSUE TITLE
Programmatically clear the queue

### ISSUE THREAD

**Issue by welsh11** [tomitrescak/meteor-uploads#92]
Hi there,

Firstly, the library is excellent, so thank you for putting it together!

I use the bootstrap uploader within a modal window and I would like some way of:
1) clearing out the queue and the file box when the modal is shown 
2) Cancelling the uploads if the modal is closed.

Is there any programmatic access available to perform these functions?

Thanks

**Comment by tomitrescak** [comment]
Check out this functionality: https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L106-L151
