### ISSUE TITLE
Deploy to xxx.meter.com crashed

### ISSUE THREAD

**Issue by HenryTi** [tomitrescak/meteor-uploads#93]
Hi Tomas,

Thank you for your meteor-uploads project. I like it.
There is one issue. When I deploy my app to xxx.meteor.com, it crashed because of the .uploads directory can't be created.
Any way to solve the problem?

Thanks,
-Henry

**Comment by tomitrescak** [comment]
This solution is not to be deployed on meteor servers. If you want to use meteor servers you have to use CollectionFS I'm afraid. If you have no permission to write .... there is nothing we can do. The only option for you is to upload directly to public directory resulting into nasty hot page refresh :/
