### ISSUE TITLE
imageVersions not creating resized images, but no error either

### ISSUE THREAD

**Issue by abcd-ca** [tomitrescak/meteor-uploads#94]
Hi, I had the same issue as this guy:
https://github.com/tomitrescak/meteor-uploads/issues/72

"I am trying to create different image sizes. I am not getting any errors at all, and the folders are being created for the different sizes. But after uploading the image, there are no images in the created folders. There is the original image in the uploads folder, but the other folders are empty. "

I do have imagemagick installed locally via brew on OS X. Is there something I'm missing?

```
UploadServer.init
	tmpDir: process.env.PWD + '/.uploads/tmp'
	uploadDir: process.env.PWD + '/.uploads/'
	checkCreateDirectories: true
	imageTypes: /.(gif|jpe?g|png)$/i
	imageVersions:
		thumbnailBig:
			width: 400
			height: 300
		thumbnailSmall:
			width: 200
			height: 100
	cacheTime: 100
	mimeTypes:
		'jpg': 'image/jpeg'
		'jpg': 'image/jpeg'
	getDirectory: (fileInfo, formData) ->
		# create a sub-directory in the uploadDir based on the content type (e.g. 'images')
		"#{formData.userID}/images"

	finished: (fileInfo, formFields) ->
		# perform a disk operation

		console.log JSON.stringify fileInfo

		return
```

**Comment by tomitrescak** [comment]
These case by case imagemagick problems are difficult to solve. Try to debug the exact command that is passed to imagemagick and paste it into terminal if imagemagick does not crash. Call it from npm version just like [here](https://github.com/tomitrescak/meteor-tomi-upload-server/blob/master/upload_server.js#L61-L66)
