### ISSUE TITLE
Semantic UI: Browse button is not in line with the progress bar on OS X

### ISSUE THREAD

**Issue by utv** [tomitrescak/meteor-uploads#95]
Hello,

I use "upload_semanticUI" and everything works right on Ubuntu but not OS X.
Position of "browse" button is not in line with the progress bar. As you can see below.
How can I fix this?
![screen shot 2558-05-25 at 20 00 53](https://cloud.githubusercontent.com/assets/2507485/7797682/d98f9f44-0319-11e5-8a44-2c0a53d54320.png)

**Comment by psing008** [comment]
I think you need to look into the CSS file and find that button's div and fix the positioning? Do a project search and find it?

**Comment by tomitrescak** [comment]
Yes, it's nasty on safari, could you fix it? Can you post correct cuss so I can incorporate it? Or maybe PR? ;)

**Comment by utv** [comment]
Sure, I will try to fix it and let you know.

**Comment by tomitrescak** [comment]
Fixed in the next release.
