### ISSUE TITLE
How to pass info to callback "finished"?

### ISSUE THREAD

**Issue by utv** [tomitrescak/meteor-uploads#97]
Hello,
Only info I can insert to database is 'fileInfo', can we pass other info to callback 'finished'?

Thank you.

**Comment by tomitrescak** [comment]
You can pass all the form data of your choice. Please check the
documentation.
On Tue, 2 Jun 2015 at 10:18 pm utv <notifications@github.com> wrote:

> Hello,
> Only info I can insert to database is 'fileInfo', can we pass other info
> to callback 'finished'?
>
> Thank you.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomitrescak/meteor-uploads/issues/97>.
>
-- 
~
Tomi Trescak / Researcher  tomi.trescak@gmail.com / 0487 261 213

**Comment by utv** [comment]
Do you mean a variable "formData"?
For example
```{{> upload_bootstrap fileTypes='.jpg' multiple=true formData=specificFormData }}
```
How can I pass my collection's id to that formData?

**Comment by tomitrescak** [comment]
That is correct. `formData` is an object. So you can fill it in using a template helper. I have updated the documentation to give an example on how to do it. Here is what I have added:

```html
<template name="home">
    <h3>Images</h3>
    {{> upload_bootstrap fileTypes='.jpg' multiple=true formData=specificFormData }}
</template>
```

```javascript
Now, you need to specify the formData in the helper:

Template.home.helpers({
  formData: function() {
    return {
      id: this._id,
      other: this.other,
      hard: 'Lolcats'
    }
  }
});
```

**Comment by tomitrescak** [comment]
I will close this issue for now, please reopen if necessary.
