### ISSUE TITLE
upload input on change event is not working

### ISSUE THREAD

**Issue by flake** [tomitrescak/meteor-uploads#98]
I am using a custom template for file upload and I want to upload image as soon as user selects the image from upload browser without having upload button, so I need to make Uploader.startUpload.call() when a "change" event occured in the file input. but meteor-uploads seems bypassing this event. Is there a way to do it?

**Comment by tomitrescak** [comment]
Sorry for the very late response. You can simply set `autoStart` on the template to automatically start the upload. Check it [here](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L214-L216).

**Comment by flake** [comment]
Thank you @tomitrescak

**Comment by smallhacks** [comment]
Hi,
I’m sorry but I have exactly the same problem and I don’t understand your answer…
If I set « {> customTemplate autoStart=true} », it doesn’t work.
Where am I wrong ?

**Comment by tomitrescak** [comment]
If it is a custom templat, you need to pass the autoStart value to the context such as following:

```
// each upload_multiple template instance holds its own local collection of files list
Template['upload'].created = function () {
  Uploader.init(this);

  // copy values to context
  if (this.data) {
    this.autoStart = this.data.autoStart;
  }
};
```

Uploader then will take the value from the template context and start the upload uatomatically.

**Comment by smallhacks** [comment]
I added :
`if (this.data) {
    this.autoStart = this.data.autoStart;
  }`
in 
`Template.customTemplate.created` 
and added autoStart=true when calling template : `{{>uploadForm autoStart=true}}`

It works, thank you very much !!!
